// ⚠️ FICHIER GÉNÉRÉ — ne pas éditer à la main.
//   node scripts/gen-depop-feuilles-app.mjs
// Source : docs/plateformes/depop/arbre.json (relevé du 2026-10-08).
// Pour le CHOIX À LA MAIN seulement (CarteRayon) : jamais une résolution
// automatique par le mot (cf. categorieParMot.feuillesDe('depop')).
// `id` = département/groupe/type — c'est lui qui part dans le job.
export const FEUILLES = [
  {"id":"everything-else/art/collectibles","chemin":["Tout le reste","Art","Objets de collection"]},
  {"id":"everything-else/art/drawing-and-illustrations","chemin":["Tout le reste","Art","Dessins et illustrations"]},
  {"id":"everything-else/art/mixed-media","chemin":["Tout le reste","Art","Médias mixtes"]},
  {"id":"everything-else/art/paintings","chemin":["Tout le reste","Art","Peintures"]},
  {"id":"everything-else/art/photography","chemin":["Tout le reste","Art","Photographie"]},
  {"id":"everything-else/art/prints","chemin":["Tout le reste","Art","À imprimé"]},
  {"id":"everything-else/art/sculptures","chemin":["Tout le reste","Art","Sculptures"]},
  {"id":"everything-else/art/stickers","chemin":["Tout le reste","Art","Autocollants"]},
  {"id":"everything-else/beauty/bath-and-body","chemin":["Tout le reste","Beauté","Bain et corps"]},
  {"id":"everything-else/beauty/fragrance","chemin":["Tout le reste","Beauté","Parfum"]},
  {"id":"everything-else/beauty/grooming","chemin":["Tout le reste","Beauté","Toilettage"]},
  {"id":"everything-else/beauty/hair-products","chemin":["Tout le reste","Beauté","Soins capillaires"]},
  {"id":"everything-else/beauty/makeup","chemin":["Tout le reste","Beauté","Maquillage"]},
  {"id":"everything-else/beauty/nails","chemin":["Tout le reste","Beauté","Ongles"]},
  {"id":"everything-else/beauty/skincare","chemin":["Tout le reste","Beauté","Soin de la peau"]},
  {"id":"everything-else/beauty/tools-and-brushes","chemin":["Tout le reste","Beauté","Outils et brosses"]},
  {"id":"everything-else/books-and-magazine/books","chemin":["Tout le reste","Livres et magazines","Livres"]},
  {"id":"everything-else/books-and-magazine/magazines","chemin":["Tout le reste","Livres et magazines","Magazines"]},
  {"id":"everything-else/face-masks/face-masks","chemin":["Tout le reste","Masques de visage","Masques de visage"]},
  {"id":"everything-else/film/cameras-and-accessories","chemin":["Tout le reste","Appareils photo et accessoires","Appareils photo et accessoires"]},
  {"id":"everything-else/home/decor-home-accesories","chemin":["Tout le reste","Accueil","Accessoires pour la maison"]},
  {"id":"everything-else/home/dinnerware","chemin":["Tout le reste","Accueil","Vaisselle"]},
  {"id":"everything-else/home/furniture","chemin":["Tout le reste","Accueil","Meubles"]},
  {"id":"everything-else/home/soft-furnishings-textiles","chemin":["Tout le reste","Accueil","Tissus d’ameublement et textiles"]},
  {"id":"everything-else/home/storage-and-organisation","chemin":["Tout le reste","Accueil","Stockage et organisation"]},
  {"id":"everything-else/music/cds-and-vinyl","chemin":["Tout le reste","Musique","CD et vinyle"]},
  {"id":"everything-else/music/musical-instruments-and-dj","chemin":["Tout le reste","Musique","Instruments de musique"]},
  {"id":"everything-else/party-supplies/cake-decor","chemin":["Tout le reste","Accessoires de fête","Décoration de gâteaux"]},
  {"id":"everything-else/party-supplies/cards-invitations-gift-wrap","chemin":["Tout le reste","Accessoires de fête","Cartes, invitations, papier cadeau"]},
  {"id":"everything-else/party-supplies/decorations","chemin":["Tout le reste","Accessoires de fête","Décorations"]},
  {"id":"everything-else/party-supplies/favours","chemin":["Tout le reste","Accessoires de fête","Articles de fête"]},
  {"id":"everything-else/party-supplies/party-hats","chemin":["Tout le reste","Accessoires de fête","Chapeaux de fête"]},
  {"id":"everything-else/sports-equipment-accesories/ball-sports","chemin":["Tout le reste","Équipements sportifs","Sports de ballon"]},
  {"id":"everything-else/sports-equipment-accesories/camping-hiking","chemin":["Tout le reste","Équipements sportifs","Camping et randonnée"]},
  {"id":"everything-else/sports-equipment-accesories/cycling","chemin":["Tout le reste","Équipements sportifs","Cyclisme"]},
  {"id":"everything-else/sports-equipment-accesories/fitness","chemin":["Tout le reste","Équipements sportifs","Fitness"]},
  {"id":"everything-else/sports-equipment-accesories/golf","chemin":["Tout le reste","Équipements sportifs","Golf"]},
  {"id":"everything-else/sports-equipment-accesories/raquet-sports","chemin":["Tout le reste","Équipements sportifs","Sports de raquette"]},
  {"id":"everything-else/sports-equipment-accesories/skates-skateboards-scooters","chemin":["Tout le reste","Équipements sportifs","Patins, skates et trottinettes"]},
  {"id":"everything-else/sports-equipment-accesories/water-sports","chemin":["Tout le reste","Équipements sportifs","Sports nautiques"]},
  {"id":"everything-else/sports-equipment-accesories/winter-sports","chemin":["Tout le reste","Équipements sportifs","Sports d'hiver"]},
  {"id":"everything-else/tech-accessories/laptop-cases-bag","chemin":["Tout le reste","Accessoires technologiques","Sacs et étuis pour ordinateurs portables"]},
  {"id":"everything-else/tech-accessories/phone-cases","chemin":["Tout le reste","Accessoires technologiques","Étuis pour téléphones"]},
  {"id":"everything-else/toys/action-figures-playsets","chemin":["Tout le reste","Jouets","Figurines et jeux de rôles"]},
  {"id":"everything-else/toys/building-sets-blocks","chemin":["Tout le reste","Jouets","Jeux de construction et blocs"]},
  {"id":"everything-else/toys/cars-vehicles","chemin":["Tout le reste","Jouets","Voitures et véhicules"]},
  {"id":"everything-else/toys/dolls-accessories","chemin":["Tout le reste","Jouets","Poupées et accessoires"]},
  {"id":"everything-else/toys/learning-toys","chemin":["Tout le reste","Jouets","Jouets d'apprentissage"]},
  {"id":"everything-else/toys/puzzles-games","chemin":["Tout le reste","Jouets","Puzzles et jeux"]},
  {"id":"everything-else/toys/stuffed-animals","chemin":["Tout le reste","Jouets","Animaux en peluche"]},
  {"id":"everything-else/toys/trading-cards","chemin":["Tout le reste","Jouets","Cartes à collectionner"]},
  {"id":"everything-else/umbrella/umbrella","chemin":["Tout le reste","Parapluies","Parapluies"]},
  {"id":"kidswear/accessories/bag","chemin":["Enfants","Accessoires","Sacs"]},
  {"id":"kidswear/accessories/belt","chemin":["Enfants","Accessoires","Ceintures"]},
  {"id":"kidswear/accessories/gloves","chemin":["Enfants","Accessoires","Gants"]},
  {"id":"kidswear/accessories/hair-accessories","chemin":["Enfants","Accessoires","Accessoires pour cheveux"]},
  {"id":"kidswear/accessories/hat","chemin":["Enfants","Accessoires","Chapeaux et casquettes"]},
  {"id":"kidswear/accessories/jewellery","chemin":["Enfants","Accessoires","Bijoux"]},
  {"id":"kidswear/accessories/other-accessories","chemin":["Enfants","Accessoires","Autre"]},
  {"id":"kidswear/accessories/scarf-wraps","chemin":["Enfants","Accessoires","Écharpes et foulards"]},
  {"id":"kidswear/accessories/sunglasses","chemin":["Enfants","Accessoires","Lunettes de soleil"]},
  {"id":"kidswear/accessories/wallet-purses","chemin":["Enfants","Accessoires","Portefeuilles et porte-cartes"]},
  {"id":"kidswear/accessories/watch","chemin":["Enfants","Accessoires","Montres"]},
  {"id":"kidswear/bottoms/jeans","chemin":["Enfants","Bas","Jeans"]},
  {"id":"kidswear/bottoms/joggers-tracksuits","chemin":["Enfants","Bas","Jogging"]},
  {"id":"kidswear/bottoms/leggings","chemin":["Enfants","Bas","Leggings"]},
  {"id":"kidswear/bottoms/other-bottoms","chemin":["Enfants","Bas","Autre"]},
  {"id":"kidswear/bottoms/shorts","chemin":["Enfants","Bas","Shorts"]},
  {"id":"kidswear/bottoms/skirts","chemin":["Enfants","Bas","Jupes"]},
  {"id":"kidswear/bottoms/trousers","chemin":["Enfants","Bas","Pantalons"]},
  {"id":"kidswear/bundles/bundles","chemin":["Enfants","Lots de vêtements","Lots de vêtements"]},
  {"id":"kidswear/coats-jackets/coats","chemin":["Enfants","Manteaux et vestes","Manteaux"]},
  {"id":"kidswear/coats-jackets/gilets","chemin":["Enfants","Manteaux et vestes","Gilets"]},
  {"id":"kidswear/coats-jackets/jackets","chemin":["Enfants","Manteaux et vestes","Vestes"]},
  {"id":"kidswear/coats-jackets/other-coats-jackets","chemin":["Enfants","Manteaux et vestes","Autre"]},
  {"id":"kidswear/dresses/babydoll-dresses","chemin":["Enfants","Robes","Babydoll dresses"]},
  {"id":"kidswear/dresses/bodycon-dresses","chemin":["Enfants","Robes","Bodycon dresses"]},
  {"id":"kidswear/dresses/casual-dresses","chemin":["Enfants","Robes","Casual dresses"]},
  {"id":"kidswear/dresses/dresses","chemin":["Enfants","Robes","Robes"]},
  {"id":"kidswear/dresses/formal-dresses","chemin":["Enfants","Robes","Formal dresses"]},
  {"id":"kidswear/dresses/going-out-dresses","chemin":["Enfants","Robes","Going out dresses"]},
  {"id":"kidswear/dresses/other-dresses","chemin":["Enfants","Robes","Other"]},
  {"id":"kidswear/dresses/prom-dresses","chemin":["Enfants","Robes","Prom dresses"]},
  {"id":"kidswear/dresses/shift-dresses","chemin":["Enfants","Robes","Shift dresses"]},
  {"id":"kidswear/dresses/shirt-dresses","chemin":["Enfants","Robes","Shirt dresses"]},
  {"id":"kidswear/dresses/summer-dresses","chemin":["Enfants","Robes","Summer dresses"]},
  {"id":"kidswear/dresses/wedding-dresses","chemin":["Enfants","Robes","Wedding dresses"]},
  {"id":"kidswear/dresses/work-dresses","chemin":["Enfants","Robes","Work dresses"]},
  {"id":"kidswear/dresses/wrap-dresses","chemin":["Enfants","Robes","Wrap dresses"]},
  {"id":"kidswear/fancy-dress/fancy-dress","chemin":["Enfants","Robe habillée","Robe habillée"]},
  {"id":"kidswear/footwear/ballet-shoes","chemin":["Enfants","Chaussures","Ballerines"]},
  {"id":"kidswear/footwear/boat-shoes","chemin":["Enfants","Chaussures","Chaussures bateau"]},
  {"id":"kidswear/footwear/boots","chemin":["Enfants","Chaussures","Bottes"]},
  {"id":"kidswear/footwear/brogues","chemin":["Enfants","Chaussures","Brogues"]},
  {"id":"kidswear/footwear/clogs","chemin":["Enfants","Chaussures","Sabots"]},
  {"id":"kidswear/footwear/courts","chemin":["Enfants","Chaussures","Courts"]},
  {"id":"kidswear/footwear/espadrilles","chemin":["Enfants","Chaussures","Espadrilles"]},
  {"id":"kidswear/footwear/first-shoes-baby-shoes","chemin":["Enfants","Chaussures","Chaussures pour bébés"]},
  {"id":"kidswear/footwear/flipflops","chemin":["Enfants","Chaussures","Tongs"]},
  {"id":"kidswear/footwear/loafers","chemin":["Enfants","Chaussures","Mocassins"]},
  {"id":"kidswear/footwear/mules","chemin":["Enfants","Chaussures","Mules"]},
  {"id":"kidswear/footwear/other-footwear","chemin":["Enfants","Chaussures","Autre"]},
  {"id":"kidswear/footwear/oxfords","chemin":["Enfants","Chaussures","Richelieu"]},
  {"id":"kidswear/footwear/sandals","chemin":["Enfants","Chaussures","Sandales"]},
  {"id":"kidswear/footwear/slides","chemin":["Enfants","Chaussures","Claquettes"]},
  {"id":"kidswear/footwear/slippers","chemin":["Enfants","Chaussures","Chaussons"]},
  {"id":"kidswear/footwear/trainers","chemin":["Enfants","Chaussures","Baskets"]},
  {"id":"kidswear/jumpsuit-and-playsuit/dungarees-overalls","chemin":["Enfants","Salopettes et combinaisons","Salopette"]},
  {"id":"kidswear/jumpsuit-and-playsuit/jumpsuit","chemin":["Enfants","Salopettes et combinaisons","Combinaisons"]},
  {"id":"kidswear/jumpsuit-and-playsuit/other-jumpsuit-and-playsuit","chemin":["Enfants","Salopettes et combinaisons","Autre"]},
  {"id":"kidswear/jumpsuit-and-playsuit/playsuit-romper","chemin":["Enfants","Salopettes et combinaisons","Combinaisons courtes"]},
  {"id":"kidswear/nightwear/other-nightwear","chemin":["Enfants","Vêtements de nuit","Autre"]},
  {"id":"kidswear/nightwear/pajamas","chemin":["Enfants","Vêtements de nuit","Pyjamas"]},
  {"id":"kidswear/nightwear/robes","chemin":["Enfants","Vêtements de nuit","Robes"]},
  {"id":"kidswear/sleepsuits-and-bodysuits/sleepsuits-babygrows","chemin":["Enfants","Grenouillères et bodys","Grenouillères et bodys"]},
  {"id":"kidswear/suits/other-suits","chemin":["Enfants","Costumes","Autre"]},
  {"id":"kidswear/suits/suits","chemin":["Enfants","Costumes","Costumes"]},
  {"id":"kidswear/suits/tailored-jackets","chemin":["Enfants","Costumes","Vestes tailleur"]},
  {"id":"kidswear/suits/tailored-trousers","chemin":["Enfants","Costumes","Pantalons habillés"]},
  {"id":"kidswear/suits/tuxedos","chemin":["Enfants","Costumes","Smokings"]},
  {"id":"kidswear/suits/waistcoats-vests","chemin":["Enfants","Costumes","Gilets de costume"]},
  {"id":"kidswear/swim-beach-wear/bikini-and-tankini-bottoms","chemin":["Enfants","Maillots de bain","Bas de bikini et de tankini"]},
  {"id":"kidswear/swim-beach-wear/bikini-and-tankini-tops","chemin":["Enfants","Maillots de bain","Hauts de bikini et de tankini"]},
  {"id":"kidswear/swim-beach-wear/bikinis-and-tankini-sets","chemin":["Enfants","Maillots de bain","Ensembles de bikinis et de tankinis"]},
  {"id":"kidswear/swim-beach-wear/cover-ups","chemin":["Enfants","Maillots de bain","Protections"]},
  {"id":"kidswear/swim-beach-wear/other-swim-beach-wear","chemin":["Enfants","Maillots de bain","Autre"]},
  {"id":"kidswear/swim-beach-wear/swim-briefs-shorts","chemin":["Enfants","Maillots de bain","Slips et shorts de bain"]},
  {"id":"kidswear/swim-beach-wear/swimsuit-one-piece","chemin":["Enfants","Maillots de bain","Maillots de bain"]},
  {"id":"kidswear/tops/blouses","chemin":["Enfants","Hauts","Blouses"]},
  {"id":"kidswear/tops/bodysuits","chemin":["Enfants","Hauts","Body"]},
  {"id":"kidswear/tops/cardigans","chemin":["Enfants","Hauts","Cardigans"]},
  {"id":"kidswear/tops/corsets","chemin":["Enfants","Hauts","Corsets"]},
  {"id":"kidswear/tops/crop-top","chemin":["Enfants","Hauts","Crop tops"]},
  {"id":"kidswear/tops/hoodies","chemin":["Enfants","Hauts","Sweat à capuche"]},
  {"id":"kidswear/tops/jerseys","chemin":["Enfants","Hauts","Maillots de sport"]},
  {"id":"kidswear/tops/jumpers","chemin":["Enfants","Hauts","Pulls"]},
  {"id":"kidswear/tops/other-tops","chemin":["Enfants","Hauts","Autre"]},
  {"id":"kidswear/tops/polo-shirts","chemin":["Enfants","Hauts","Polo"]},
  {"id":"kidswear/tops/shirts","chemin":["Enfants","Hauts","T-shirts (Shirts)"]},
  {"id":"kidswear/tops/sweatshirts","chemin":["Enfants","Hauts","Sweat-shirts"]},
  {"id":"kidswear/tops/tshirts","chemin":["Enfants","Hauts","T-shirts"]},
  {"id":"kidswear/tops/vests-tanks-camis","chemin":["Enfants","Hauts","Vestes"]},
  {"id":"menswear/accessories/bag","chemin":["Homme","Accessoires","Sacs"]},
  {"id":"menswear/accessories/belt","chemin":["Homme","Accessoires","Ceintures"]},
  {"id":"menswear/accessories/gloves","chemin":["Homme","Accessoires","Gants"]},
  {"id":"menswear/accessories/hair-accessories","chemin":["Homme","Accessoires","Accessoires pour cheveux"]},
  {"id":"menswear/accessories/hat","chemin":["Homme","Accessoires","Chapeaux et casquettes"]},
  {"id":"menswear/accessories/jewellery","chemin":["Homme","Accessoires","Bijoux"]},
  {"id":"menswear/accessories/other-accessories","chemin":["Homme","Accessoires","Autre"]},
  {"id":"menswear/accessories/scarf-wraps","chemin":["Homme","Accessoires","Écharpes et foulards"]},
  {"id":"menswear/accessories/sunglasses","chemin":["Homme","Accessoires","Lunettes de soleil"]},
  {"id":"menswear/accessories/wallet-purses","chemin":["Homme","Accessoires","Portefeuilles et porte-cartes"]},
  {"id":"menswear/accessories/watch","chemin":["Homme","Accessoires","Montres"]},
  {"id":"menswear/bottoms/jeans","chemin":["Homme","Bas","Jeans"]},
  {"id":"menswear/bottoms/joggers-tracksuits","chemin":["Homme","Bas","Jogging"]},
  {"id":"menswear/bottoms/leggings","chemin":["Homme","Bas","Leggings"]},
  {"id":"menswear/bottoms/other-bottoms","chemin":["Homme","Bas","Autre"]},
  {"id":"menswear/bottoms/shorts","chemin":["Homme","Bas","Shorts"]},
  {"id":"menswear/bottoms/skirts","chemin":["Homme","Bas","Jupes"]},
  {"id":"menswear/bottoms/trousers","chemin":["Homme","Bas","Pantalons"]},
  {"id":"menswear/coats-jackets/coats","chemin":["Homme","Manteaux et vestes","Manteaux"]},
  {"id":"menswear/coats-jackets/gilets","chemin":["Homme","Manteaux et vestes","Gilets"]},
  {"id":"menswear/coats-jackets/jackets","chemin":["Homme","Manteaux et vestes","Vestes"]},
  {"id":"menswear/coats-jackets/other-coats-jackets","chemin":["Homme","Manteaux et vestes","Autre"]},
  {"id":"menswear/fancy-dress/fancy-dress","chemin":["Homme","Robe habillée","Robe habillée"]},
  {"id":"menswear/footwear/ballet-shoes","chemin":["Homme","Chaussures","Ballerines"]},
  {"id":"menswear/footwear/boat-shoes","chemin":["Homme","Chaussures","Chaussures bateau"]},
  {"id":"menswear/footwear/boots","chemin":["Homme","Chaussures","Bottes"]},
  {"id":"menswear/footwear/brogues","chemin":["Homme","Chaussures","Brogues"]},
  {"id":"menswear/footwear/clogs","chemin":["Homme","Chaussures","Sabots"]},
  {"id":"menswear/footwear/courts","chemin":["Homme","Chaussures","Courts"]},
  {"id":"menswear/footwear/espadrilles","chemin":["Homme","Chaussures","Espadrilles"]},
  {"id":"menswear/footwear/first-shoes-baby-shoes","chemin":["Homme","Chaussures","Chaussures pour bébés"]},
  {"id":"menswear/footwear/flipflops","chemin":["Homme","Chaussures","Tongs"]},
  {"id":"menswear/footwear/loafers","chemin":["Homme","Chaussures","Mocassins"]},
  {"id":"menswear/footwear/mules","chemin":["Homme","Chaussures","Mules"]},
  {"id":"menswear/footwear/other-footwear","chemin":["Homme","Chaussures","Autre"]},
  {"id":"menswear/footwear/oxfords","chemin":["Homme","Chaussures","Richelieu"]},
  {"id":"menswear/footwear/sandals","chemin":["Homme","Chaussures","Sandales"]},
  {"id":"menswear/footwear/slides","chemin":["Homme","Chaussures","Claquettes"]},
  {"id":"menswear/footwear/slippers","chemin":["Homme","Chaussures","Chaussons"]},
  {"id":"menswear/footwear/trainers","chemin":["Homme","Chaussures","Baskets"]},
  {"id":"menswear/jumpsuit-and-playsuit/dungarees-overalls","chemin":["Homme","Salopettes et combinaisons","Salopette"]},
  {"id":"menswear/jumpsuit-and-playsuit/jumpsuit","chemin":["Homme","Salopettes et combinaisons","Combinaisons"]},
  {"id":"menswear/jumpsuit-and-playsuit/other-jumpsuit-and-playsuit","chemin":["Homme","Salopettes et combinaisons","Autre"]},
  {"id":"menswear/jumpsuit-and-playsuit/playsuit-romper","chemin":["Homme","Salopettes et combinaisons","Combinaisons courtes"]},
  {"id":"menswear/nightwear/other-nightwear","chemin":["Homme","Vêtements de nuit","Autre"]},
  {"id":"menswear/nightwear/pajamas","chemin":["Homme","Vêtements de nuit","Pyjamas"]},
  {"id":"menswear/nightwear/robes","chemin":["Homme","Vêtements de nuit","Robes"]},
  {"id":"menswear/suits/other-suits","chemin":["Homme","Costumes","Autre"]},
  {"id":"menswear/suits/suits","chemin":["Homme","Costumes","Costumes"]},
  {"id":"menswear/suits/tailored-jackets","chemin":["Homme","Costumes","Vestes tailleur"]},
  {"id":"menswear/suits/tailored-trousers","chemin":["Homme","Costumes","Pantalons habillés"]},
  {"id":"menswear/suits/tuxedos","chemin":["Homme","Costumes","Smokings"]},
  {"id":"menswear/suits/waistcoats-vests","chemin":["Homme","Costumes","Gilets de costume"]},
  {"id":"menswear/swim-beach-wear/bikini-and-tankini-bottoms","chemin":["Homme","Maillots de bain","Bas de bikini et de tankini"]},
  {"id":"menswear/swim-beach-wear/bikini-and-tankini-tops","chemin":["Homme","Maillots de bain","Hauts de bikini et de tankini"]},
  {"id":"menswear/swim-beach-wear/bikinis-and-tankini-sets","chemin":["Homme","Maillots de bain","Ensembles de bikinis et de tankinis"]},
  {"id":"menswear/swim-beach-wear/cover-ups","chemin":["Homme","Maillots de bain","Protections"]},
  {"id":"menswear/swim-beach-wear/other-swim-beach-wear","chemin":["Homme","Maillots de bain","Autre"]},
  {"id":"menswear/swim-beach-wear/swim-briefs-shorts","chemin":["Homme","Maillots de bain","Slips et shorts de bain"]},
  {"id":"menswear/swim-beach-wear/swimsuit-one-piece","chemin":["Homme","Maillots de bain","Maillots de bain"]},
  {"id":"menswear/tops/blouses","chemin":["Homme","Hauts","Blouses"]},
  {"id":"menswear/tops/bodysuits","chemin":["Homme","Hauts","Body"]},
  {"id":"menswear/tops/cardigans","chemin":["Homme","Hauts","Cardigans"]},
  {"id":"menswear/tops/corsets","chemin":["Homme","Hauts","Corsets"]},
  {"id":"menswear/tops/crop-top","chemin":["Homme","Hauts","Crop tops"]},
  {"id":"menswear/tops/hoodies","chemin":["Homme","Hauts","Sweat à capuche"]},
  {"id":"menswear/tops/jerseys","chemin":["Homme","Hauts","Maillots de sport"]},
  {"id":"menswear/tops/jumpers","chemin":["Homme","Hauts","Pulls"]},
  {"id":"menswear/tops/other-tops","chemin":["Homme","Hauts","Autre"]},
  {"id":"menswear/tops/polo-shirts","chemin":["Homme","Hauts","Polo"]},
  {"id":"menswear/tops/shirts","chemin":["Homme","Hauts","T-shirts (Shirts)"]},
  {"id":"menswear/tops/sweatshirts","chemin":["Homme","Hauts","Sweat-shirts"]},
  {"id":"menswear/tops/tshirts","chemin":["Homme","Hauts","T-shirts"]},
  {"id":"menswear/tops/vests-tanks-camis","chemin":["Homme","Hauts","Vestes"]},
  {"id":"menswear/underwear/bandeaus","chemin":["Homme","Sous-vêtements","Bandeaux"]},
  {"id":"menswear/underwear/boxers-and-briefs","chemin":["Homme","Sous-vêtements","Boxers et caleçons"]},
  {"id":"menswear/underwear/bras","chemin":["Homme","Sous-vêtements","Soutien-gorge"]},
  {"id":"menswear/underwear/hosiery-tights","chemin":["Homme","Sous-vêtements","Collants"]},
  {"id":"menswear/underwear/other-underwear","chemin":["Homme","Sous-vêtements","Autre"]},
  {"id":"menswear/underwear/panties","chemin":["Homme","Sous-vêtements","Culottes"]},
  {"id":"menswear/underwear/shapewear","chemin":["Homme","Sous-vêtements","Gainant"]},
  {"id":"menswear/underwear/socks","chemin":["Homme","Sous-vêtements","Chaussettes"]},
  {"id":"menswear/underwear/vest-undershirts","chemin":["Homme","Sous-vêtements","Vestes"]},
  {"id":"womenswear/accessories/bag","chemin":["Femme","Accessoires","Sacs"]},
  {"id":"womenswear/accessories/belt","chemin":["Femme","Accessoires","Ceintures"]},
  {"id":"womenswear/accessories/gloves","chemin":["Femme","Accessoires","Gants"]},
  {"id":"womenswear/accessories/hair-accessories","chemin":["Femme","Accessoires","Accessoires pour cheveux"]},
  {"id":"womenswear/accessories/hat","chemin":["Femme","Accessoires","Chapeaux et casquettes"]},
  {"id":"womenswear/accessories/jewellery","chemin":["Femme","Accessoires","Bijoux"]},
  {"id":"womenswear/accessories/other-accessories","chemin":["Femme","Accessoires","Autre"]},
  {"id":"womenswear/accessories/scarf-wraps","chemin":["Femme","Accessoires","Écharpes et foulards"]},
  {"id":"womenswear/accessories/sunglasses","chemin":["Femme","Accessoires","Lunettes de soleil"]},
  {"id":"womenswear/accessories/wallet-purses","chemin":["Femme","Accessoires","Portefeuilles et porte-cartes"]},
  {"id":"womenswear/accessories/watch","chemin":["Femme","Accessoires","Montres"]},
  {"id":"womenswear/bottoms/jeans","chemin":["Femme","Bas","Jeans"]},
  {"id":"womenswear/bottoms/joggers-tracksuits","chemin":["Femme","Bas","Jogging"]},
  {"id":"womenswear/bottoms/leggings","chemin":["Femme","Bas","Leggings"]},
  {"id":"womenswear/bottoms/other-bottoms","chemin":["Femme","Bas","Autre"]},
  {"id":"womenswear/bottoms/shorts","chemin":["Femme","Bas","Shorts"]},
  {"id":"womenswear/bottoms/skirts","chemin":["Femme","Bas","Jupes"]},
  {"id":"womenswear/bottoms/trousers","chemin":["Femme","Bas","Pantalons"]},
  {"id":"womenswear/coats-jackets/coats","chemin":["Femme","Manteaux et vestes","Manteaux"]},
  {"id":"womenswear/coats-jackets/gilets","chemin":["Femme","Manteaux et vestes","Gilets"]},
  {"id":"womenswear/coats-jackets/jackets","chemin":["Femme","Manteaux et vestes","Vestes"]},
  {"id":"womenswear/coats-jackets/other-coats-jackets","chemin":["Femme","Manteaux et vestes","Autre"]},
  {"id":"womenswear/dresses/babydoll-dresses","chemin":["Femme","Robes","Babydoll dresses"]},
  {"id":"womenswear/dresses/bodycon-dresses","chemin":["Femme","Robes","Bodycon dresses"]},
  {"id":"womenswear/dresses/casual-dresses","chemin":["Femme","Robes","Casual dresses"]},
  {"id":"womenswear/dresses/dresses","chemin":["Femme","Robes","Robes"]},
  {"id":"womenswear/dresses/formal-dresses","chemin":["Femme","Robes","Formal dresses"]},
  {"id":"womenswear/dresses/going-out-dresses","chemin":["Femme","Robes","Going out dresses"]},
  {"id":"womenswear/dresses/other-dresses","chemin":["Femme","Robes","Other"]},
  {"id":"womenswear/dresses/prom-dresses","chemin":["Femme","Robes","Prom dresses"]},
  {"id":"womenswear/dresses/shift-dresses","chemin":["Femme","Robes","Shift dresses"]},
  {"id":"womenswear/dresses/shirt-dresses","chemin":["Femme","Robes","Shirt dresses"]},
  {"id":"womenswear/dresses/summer-dresses","chemin":["Femme","Robes","Summer dresses"]},
  {"id":"womenswear/dresses/wedding-dresses","chemin":["Femme","Robes","Wedding dresses"]},
  {"id":"womenswear/dresses/work-dresses","chemin":["Femme","Robes","Work dresses"]},
  {"id":"womenswear/dresses/wrap-dresses","chemin":["Femme","Robes","Wrap dresses"]},
  {"id":"womenswear/fancy-dress/fancy-dress","chemin":["Femme","Robe habillée","Robe habillée"]},
  {"id":"womenswear/footwear/ballet-shoes","chemin":["Femme","Chaussures","Ballerines"]},
  {"id":"womenswear/footwear/boat-shoes","chemin":["Femme","Chaussures","Chaussures bateau"]},
  {"id":"womenswear/footwear/boots","chemin":["Femme","Chaussures","Bottes"]},
  {"id":"womenswear/footwear/brogues","chemin":["Femme","Chaussures","Brogues"]},
  {"id":"womenswear/footwear/clogs","chemin":["Femme","Chaussures","Sabots"]},
  {"id":"womenswear/footwear/courts","chemin":["Femme","Chaussures","Courts"]},
  {"id":"womenswear/footwear/espadrilles","chemin":["Femme","Chaussures","Espadrilles"]},
  {"id":"womenswear/footwear/first-shoes-baby-shoes","chemin":["Femme","Chaussures","Chaussures pour bébés"]},
  {"id":"womenswear/footwear/flipflops","chemin":["Femme","Chaussures","Tongs"]},
  {"id":"womenswear/footwear/loafers","chemin":["Femme","Chaussures","Mocassins"]},
  {"id":"womenswear/footwear/mules","chemin":["Femme","Chaussures","Mules"]},
  {"id":"womenswear/footwear/other-footwear","chemin":["Femme","Chaussures","Autre"]},
  {"id":"womenswear/footwear/oxfords","chemin":["Femme","Chaussures","Richelieu"]},
  {"id":"womenswear/footwear/sandals","chemin":["Femme","Chaussures","Sandales"]},
  {"id":"womenswear/footwear/slides","chemin":["Femme","Chaussures","Claquettes"]},
  {"id":"womenswear/footwear/slippers","chemin":["Femme","Chaussures","Chaussons"]},
  {"id":"womenswear/footwear/trainers","chemin":["Femme","Chaussures","Baskets"]},
  {"id":"womenswear/jumpsuit-and-playsuit/dungarees-overalls","chemin":["Femme","Salopettes et combinaisons","Salopette"]},
  {"id":"womenswear/jumpsuit-and-playsuit/jumpsuit","chemin":["Femme","Salopettes et combinaisons","Combinaisons"]},
  {"id":"womenswear/jumpsuit-and-playsuit/other-jumpsuit-and-playsuit","chemin":["Femme","Salopettes et combinaisons","Autre"]},
  {"id":"womenswear/jumpsuit-and-playsuit/playsuit-romper","chemin":["Femme","Salopettes et combinaisons","Combinaisons courtes"]},
  {"id":"womenswear/nightwear/other-nightwear","chemin":["Femme","Vêtements de nuit","Autre"]},
  {"id":"womenswear/nightwear/pajamas","chemin":["Femme","Vêtements de nuit","Pyjamas"]},
  {"id":"womenswear/nightwear/robes","chemin":["Femme","Vêtements de nuit","Robes"]},
  {"id":"womenswear/suits/other-suits","chemin":["Femme","Costumes","Autre"]},
  {"id":"womenswear/suits/suits","chemin":["Femme","Costumes","Costumes"]},
  {"id":"womenswear/suits/tailored-jackets","chemin":["Femme","Costumes","Vestes tailleur"]},
  {"id":"womenswear/suits/tailored-trousers","chemin":["Femme","Costumes","Pantalons habillés"]},
  {"id":"womenswear/suits/tuxedos","chemin":["Femme","Costumes","Smokings"]},
  {"id":"womenswear/suits/waistcoats-vests","chemin":["Femme","Costumes","Gilets de costume"]},
  {"id":"womenswear/swim-beach-wear/bikini-and-tankini-bottoms","chemin":["Femme","Maillots de bain","Bas de bikini et de tankini"]},
  {"id":"womenswear/swim-beach-wear/bikini-and-tankini-tops","chemin":["Femme","Maillots de bain","Hauts de bikini et de tankini"]},
  {"id":"womenswear/swim-beach-wear/bikinis-and-tankini-sets","chemin":["Femme","Maillots de bain","Ensembles de bikinis et de tankinis"]},
  {"id":"womenswear/swim-beach-wear/cover-ups","chemin":["Femme","Maillots de bain","Protections"]},
  {"id":"womenswear/swim-beach-wear/other-swim-beach-wear","chemin":["Femme","Maillots de bain","Autre"]},
  {"id":"womenswear/swim-beach-wear/swim-briefs-shorts","chemin":["Femme","Maillots de bain","Slips et shorts de bain"]},
  {"id":"womenswear/swim-beach-wear/swimsuit-one-piece","chemin":["Femme","Maillots de bain","Maillots de bain"]},
  {"id":"womenswear/tops/blouses","chemin":["Femme","Hauts","Blouses"]},
  {"id":"womenswear/tops/bodysuits","chemin":["Femme","Hauts","Body"]},
  {"id":"womenswear/tops/cardigans","chemin":["Femme","Hauts","Cardigans"]},
  {"id":"womenswear/tops/corsets","chemin":["Femme","Hauts","Corsets"]},
  {"id":"womenswear/tops/crop-top","chemin":["Femme","Hauts","Crop tops"]},
  {"id":"womenswear/tops/hoodies","chemin":["Femme","Hauts","Sweat à capuche"]},
  {"id":"womenswear/tops/jerseys","chemin":["Femme","Hauts","Maillots de sport"]},
  {"id":"womenswear/tops/jumpers","chemin":["Femme","Hauts","Pulls"]},
  {"id":"womenswear/tops/other-tops","chemin":["Femme","Hauts","Autre"]},
  {"id":"womenswear/tops/polo-shirts","chemin":["Femme","Hauts","Polo"]},
  {"id":"womenswear/tops/shirts","chemin":["Femme","Hauts","T-shirts (Shirts)"]},
  {"id":"womenswear/tops/sweatshirts","chemin":["Femme","Hauts","Sweat-shirts"]},
  {"id":"womenswear/tops/tshirts","chemin":["Femme","Hauts","T-shirts"]},
  {"id":"womenswear/tops/vests-tanks-camis","chemin":["Femme","Hauts","Vestes"]},
  {"id":"womenswear/underwear/bandeaus","chemin":["Femme","Sous-vêtements","Bandeaux"]},
  {"id":"womenswear/underwear/boxers-and-briefs","chemin":["Femme","Sous-vêtements","Boxers et caleçons"]},
  {"id":"womenswear/underwear/bras","chemin":["Femme","Sous-vêtements","Soutien-gorge"]},
  {"id":"womenswear/underwear/hosiery-tights","chemin":["Femme","Sous-vêtements","Collants"]},
  {"id":"womenswear/underwear/other-underwear","chemin":["Femme","Sous-vêtements","Autre"]},
  {"id":"womenswear/underwear/panties","chemin":["Femme","Sous-vêtements","Culottes"]},
  {"id":"womenswear/underwear/shapewear","chemin":["Femme","Sous-vêtements","Gainant"]},
  {"id":"womenswear/underwear/socks","chemin":["Femme","Sous-vêtements","Chaussettes"]},
  {"id":"womenswear/underwear/vest-undershirts","chemin":["Femme","Sous-vêtements","Vestes"]},
];
