-- ═══════════════════════════════════════════════════════════════════════════
-- UN RÉGLAGE DE coin_config NE CHANGE PLUS EN SILENCE (04/10, point 7)
-- ═══════════════════════════════════════════════════════════════════════════
-- Le plafond journalier des republications Premium est repassé de 50 à 170
-- après le 22/09 — posé à la main, updated_at intact, aucune trace — alors
-- que Nico l'avait fixé à 50 le 12/09 (« 170 c'était une erreur »). Résultat
-- le 04/10 : 84 republications Vinted depuis minuit chez nadegemarcelin78
-- (restreinte par Vinted en août à ce rythme). Remis à 50 le 04/10
-- (scripts/reparations/20261004_plafond_republication_premium_50.sql).
-- Désormais : toute modification d'une valeur date sa ligne (updated_at) et
-- s'écrit dans coin_config_journal (clé, avant, après, qui, quand) — une
-- écriture à la main reste possible, mais elle se voit.
-- Idempotente.

CREATE TABLE IF NOT EXISTS public.coin_config_journal (
  id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  key        text NOT NULL,
  avant      numeric,
  apres      numeric,
  par        text,
  le         timestamptz NOT NULL DEFAULT now()
);
ALTER TABLE public.coin_config_journal ENABLE ROW LEVEL SECURITY;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.coin_config_journal TO authenticated;
GRANT ALL ON public.coin_config_journal TO service_role;

CREATE OR REPLACE FUNCTION public.coin_config_trace()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public', 'pg_temp'
AS $function$
BEGIN
  IF NEW.value IS DISTINCT FROM OLD.value THEN
    NEW.updated_at := now();
    INSERT INTO coin_config_journal (key, avant, apres, par)
    VALUES (NEW.key, OLD.value, NEW.value, COALESCE(NULLIF(current_setting('request.jwt.claims', true), '')::jsonb ->> 'role', current_user));
  END IF;
  RETURN NEW;
END;
$function$;

DROP TRIGGER IF EXISTS coin_config_trace ON public.coin_config;
CREATE TRIGGER coin_config_trace
  BEFORE UPDATE OF value ON public.coin_config
  FOR EACH ROW EXECUTE FUNCTION public.coin_config_trace();
