-- ⚠️ FICHIER GÉNÉRÉ — ne pas éditer à la main.
--   node scripts/gen-opla-catalogue.mjs
--
-- L'ARBRE OPLA EN BASE, dans platform_category_aspects, exactement comme
-- Vinted : c'est cette table que get-pending-jobs sert au needs_user typé.
-- Source : docs/opla/*.tsv (phase 0, revérifiés contre le live le 2026-09-16).
--
-- DEUX SORTES DE LIGNES, et c'est tout :
--   field_key='category' — 129 lignes, une par nœud AYANT des enfants
--     (clé 'ROOT' pour le niveau racine). allowed_values = [{code,title}] des
--     enfants DIRECTS. C'est ce qui permet de proposer LE NIVEAU QUI A ÉCHOUÉ
--     au lieu des racines (défaut Blaf69 du 16/09 côté Vinted).
--   field_key='size'     — 397 lignes, une par feuille AYANT une grille.
--     ⛔ Les 489 feuilles en G0 n'ont PAS de ligne : une catégorie sans champ
--     Taille ne doit pas en proposer une liste vide.
--
-- ⛔ IDEMPOTENTE. Réappliquée, elle réécrit les mêmes valeurs et ne touche
--    AUCUNE autre plateforme (le ON CONFLICT porte sur la clé complète, et
--    tout est borné à platform='opla').
-- ⛔ source='manual' : la colonne porte une CHECK fermée (dom / server_400 /
--    manual) — lue en prod le 16/09, après un premier envoi refusé en 23514.
--    Ces lignes ne sont ni un relevé DOM ni un refus serveur : elles sont
--    posées délibérément depuis docs/opla/*.tsv. 'manual' est le seul des trois
--    qui dise vrai, et l'ouvrir à une 4e valeur aurait demandé un DDL sur une
--    table que quatre plateformes alimentent — hors du périmètre de ce lot.
-- ⛔ N'ACTIVE RIEN : ce sont des données. OPLA_ACTIF et
--    PLATFORM_HANDLERS.opla.implemented restent false.

-- ⛔ AUCUN DDL ICI, ET C'EST UNE CORRECTION DU 16/09 AVANT APPLICATION.
-- Cette migration créait `platform_category_aspects_cle_unique` en
-- `if not exists`. Or l'unicité (platform, category_key, field_key) EXISTE
-- DÉJÀ, sous le nom que Postgres a donné à la contrainte de table :
-- `platform_category_aspects_platform_category_key_field_key_key` (lu en prod).
-- `if not exists` ne teste que le NOM : un second index unique, identique
-- colonne pour colonne, serait parti en prod pour rien — écriture ralentie sur
-- une table que quatre plateformes alimentent en continu.
-- Le ON CONFLICT ci-dessous vise par LISTE DE COLONNES, pas par nom : il
-- s'appuie sur la contrainte existante, sans rien créer.

begin;

-- niveaux de choix 1 à 45 sur 129
with niveaux (category_key, allowed_values) as (values
  ('ROOT', '[{"code":"CULTURE_ET_LOISIR","title":"Culture et Loisirs"},{"code":"TOYS_AND_GAMES","title":"Jeux et jouets"},{"code":"WOMEN_ROOT","title":"Femmes"},{"code":"MENS","title":"Hommes"},{"code":"CHILDREN_NEW","title":"Enfants"},{"code":"MAISON","title":"Maison"},{"code":"SPORT","title":"Sport"},{"code":"FAIT_MAIN","title":"Fait main"}]'::jsonb),
  ('ACCESSORIES_BOYS_NEW', '[{"code":"CAPS_BOYS_NEW","title":"Casquettes, chapeaux et bonnets"},{"code":"GLOVES_BOYS_NEW","title":"Gants"},{"code":"SCARVES_BOYS_NEW","title":"Écharpes et châles"},{"code":"BELTS_BOYS_NEW","title":"Ceintures"},{"code":"WALLETS_BOYS_NEW","title":"Porte-monnaie"},{"code":"BOWS_BOYS_NEW","title":"Nœuds papillon et cravattes"},{"code":"BOYS_ACC_NEW","title":"Autres accessoires"}]'::jsonb),
  ('ACCESSORIES_GIRLS_NEW', '[{"code":"HATS_GIRLS_NEW","title":"Casquettes, chapeaux et bonnets"},{"code":"GLOVES_GIRLS_NEW","title":"Gants"},{"code":"SCARVES_GIRLS_NEW","title":"Écharpes et châles"},{"code":"BELTS_GIRLS_NEW","title":"Ceintures"},{"code":"HAIR_ACC_GIRLS_NEW","title":"Bandeaux et barrettes cheveux"},{"code":"JEWELRY_GIRLS_NEW","title":"Bijoux"},{"code":"KIDS_WALLETS_NEW","title":"Porte-monnaie"},{"code":"OTHERS_ACC_GIRLS","title":"Autres accessoires"}]'::jsonb),
  ('ACCESSORIES_JEWELLERY', '[{"code":"WOMEN_BANDANAS_HEADSCARVES","title":"Bandanas et foulards pour cheveux"},{"code":"BELTS","title":"Ceintures"},{"code":"GLOVES","title":"Gants"},{"code":"W_HAIR_ACCESSORIES","title":"Accessoires pour cheveux"},{"code":"JEWELRY","title":"Bijoux"},{"code":"WOM_ACC_HATS_CAPS","title":"Chapeaux & casquettes"},{"code":"KEY_RINGS","title":"Porte-clés"},{"code":"WOM_ACC_SCARVES_SHAWLS","title":"Écharpes et châles"},{"code":"SUNGLASSES","title":"Lunettes de soleil"},{"code":"W_ACC_UMBRELLAS","title":"Parapluies"},{"code":"WATCHES","title":"Montres"},{"code":"W_OTHER_ACCESSORIES","title":"Autres accessoires"}]'::jsonb),
  ('ACTION_FIGURES_NEW', '[{"code":"TOY_FIGURES","title":"Figurines"},{"code":"TOY_FIGURE_ACCESSORIES","title":"Accessoires"},{"code":"TOY_FIGURE_PLAYSET","title":"Sets de jeux"}]'::jsonb),
  ('BABY_ACCESSORIES', '[{"code":"BUGGY_COVERS","title":"Habillages pluie et ombrelles"},{"code":"BUGGY_CUPHOLDER","title":"Porte-gobelets et plateaux"},{"code":"BUGGY_FOOTMUFF","title":"Chancelières de poussette"},{"code":"BUGGY_ORGANISER","title":"Organisateurs et filets"},{"code":"BUGGY_PARTS","title":"Pièces détachées de poussette"},{"code":"BABY_CAR_MIRROR","title":"Miroirs de voiture"},{"code":"BABY_CAR_SUNSHADE","title":"Pare-soleil de voiture"},{"code":"CARSEAT_INSERTS","title":"Réducteurs pour siège auto"},{"code":"CARSEAT_TRAVELBAG","title":"Housses de siège auto"},{"code":"CARSEAT_FOOTMUFF","title":"Chancelières de siège auto"},{"code":"CARSEAT_ACC_OTHER","title":"Autres accessoires voiture"},{"code":"KID_NESTS","title":"Réducteurs de lit"},{"code":"CHILDPROOFING_ACC","title":"Accessoires de sécurité"},{"code":"KID_HEARING_PROTECTION","title":"Protections auditives"},{"code":"KID_SAFETY_HARNESS","title":"Laisses et harnais"},{"code":"KID_HUMIDIFIERS","title":"Humidificateurs"},{"code":"NASAL_ASPIRATOR","title":"Mouche-bébés"},{"code":"POSTPARTUM_CARE","title":"Soins post-partum"},{"code":"PREGNANCY_PILLOW","title":"Coussins de grossesse"},{"code":"PREGNANCY_BELT","title":"Ceintures de grossesse"},{"code":"KID_SCALES","title":"Pèse-bébés"},{"code":"KID_THERMOMETERS","title":"Thermomètres bébé"}]'::jsonb),
  ('BABY_ACTIVITIES_TOYS', '[{"code":"BABY_ACTIVITY_CENTER","title":"Centres d''activités et trotteurs"},{"code":"BABY_GYMS","title":"Tapis d''éveil et d''activités"},{"code":"BATH_TOYS","title":"Jouets de bain"},{"code":"PUSH_PULL_TOYS","title":"Jouets à pousser et à tirer"},{"code":"RATTLES_TOYS","title":"Hochets"},{"code":"SORT_STACK_TOYS","title":"Jouets de tri et d''empilement"},{"code":"TEETHERS","title":"Jouets de dentition"}]'::jsonb),
  ('BABY_CARRIERS', '[{"code":"BABY_SLINGS","title":"Écharpes et slings"},{"code":"BABY_SOFT_CARRIERS","title":"Porte-bébé souples"},{"code":"BABY_HIP_CARRIERS","title":"Porte-bébé de hanche"}]'::jsonb),
  ('BABY_CUP_DISHES_UTENSILS', '[{"code":"BABY_CUTLERY","title":"Couverts"},{"code":"BABY_PLATE_BOWL","title":"Assiettes et bols"},{"code":"BABY_DINNER_SETS","title":"Coffrets repas"},{"code":"BABY_SIPPY_CUPS","title":"Tasses d''apprentissage"},{"code":"BABY_WATER_BOTTLES","title":"Gourdes"}]'::jsonb),
  ('BABY_ROOM_DECOR', '[{"code":"KID_BABY_ALBUM","title":"Albums photo"},{"code":"KID_GROWTH_CHART","title":"Toises"},{"code":"BABY_MOBILE","title":"Mobiles"},{"code":"BABY_MILESTONE_CARD","title":"Cartes étapes et accessoires photo"},{"code":"KID_MONEY_BOX","title":"Tirelires"},{"code":"KID_PHOTO_FRAME","title":"Cadres photo"},{"code":"KID_WALL_DECOR","title":"Décorations murales"}]'::jsonb),
  ('BAGS', '[{"code":"MEN_ACC_BAG_BACKPACKS","title":"Sacs à dos"},{"code":"MEN_BRIEFCASES","title":"Mallettes"},{"code":"MEN_ACC_BUMBAGS","title":"Sacs banane"},{"code":"MEN_GYM_BAGS","title":"Sacs de sport"},{"code":"MEN_HOLDALLS","title":"Fourre-tout et sacs marins"},{"code":"MEN_LUGGAGE","title":"Bagages et valises"},{"code":"MEN_ACC_SATCHELS","title":"Cartables et sacoches"},{"code":"MEN_ACC_BAG_SHOULDER_BAGS","title":"Sacs à bandoulière"},{"code":"WALLETS","title":"Porte-monnaie"},{"code":"MEN_WASH_BAGS","title":"Trousses de toilette"}]'::jsonb),
  ('BAGS_BACKPACKS', '[{"code":"BACKPACKS","title":"Sacs à dos"},{"code":"WOMEN_BASKET_BAGS","title":"Sacs panier"},{"code":"WOMEN_BEACH_BAGS","title":"Sacs de plage"},{"code":"WOMEN_BRIEFCASES","title":"Mallettes"},{"code":"W_BUM_BAGS","title":"Sacs banane"},{"code":"CLUTCHES","title":"Pochettes"},{"code":"WOMEN_GARMENT_BAGS","title":"Housses pour vêtements"},{"code":"WOMEN_GYM_BAGS","title":"Sacs de sport"},{"code":"HANDBAGS","title":"Sacs à main"},{"code":"W_HOLDALLS","title":"Fourre-tout et sacs marins"},{"code":"W_LUGGAGE","title":"Sacs de voyage"},{"code":"MAKE_UP_BAGS","title":"Trousses à maquillage"},{"code":"SATCHELS_NEW","title":"Cartables et sacoches"},{"code":"SHOULDER_BAGS","title":"Sacs à bandoulière"},{"code":"TOTE_BAGS","title":"Sacs fourre-tout"},{"code":"PURSES","title":"Porte-monnaie"},{"code":"WOMEN_WRISTLETS","title":"Bracelets"},{"code":"WASH_BAGS","title":"Trousses de toilette"},{"code":"WOMEN_BUCKET_BAGS","title":"Sacs seau"},{"code":"WOMEN_HOBO_BAGS","title":"Besaces"}]'::jsonb),
  ('BEAUTY', '[{"code":"BEAUTY_PERFUMES","title":"Parfums"},{"code":"BEAUTY_MAKEUP","title":"Maquillage"},{"code":"BEAUTY_SKINCARE_FACE","title":"Soins visage"},{"code":"BEAUTY_BODYCARE","title":"Soins corps et douche"},{"code":"BEAUTY_HAIRCARE","title":"Soins cheveux"},{"code":"BEAUTY_TOOLS","title":"Outils et accessoires beauté"},{"code":"BEAUTY_BATH_SPA","title":"Bain et spa"}]'::jsonb),
  ('BLAZERS', '[{"code":"WOM_BLA_BLAZERS","title":"Blazers"},{"code":"W_PANTSUITS","title":"Ensembles tailleur/pantalon"},{"code":"W_SKIRT_SUITS","title":"Jupes et robes tailleurs"},{"code":"W_SUIT_SEPARATES","title":"Tailleurs pièces séparées"},{"code":"W_OTHER_SUITS_BLAZERS","title":"Autres ensembles & tailleurs"}]'::jsonb),
  ('BOTTLE_FEEDING', '[{"code":"BABY_BOTTLE","title":"Biberons"},{"code":"BABY_BOTTLE_TEAT","title":"Tétines"},{"code":"BOTTLE_DRYING_RACK","title":"Séchoirs à linge"},{"code":"BOTTLE_BRUSHES","title":"Goupillons"},{"code":"BOTTLE_WARMERS","title":"Chauffe-biberon"},{"code":"BABY_FORMULA_MAKER","title":"Préparateurs de biberons"},{"code":"BABY_FORMULA_STORAGE","title":"Boîtes doseuses"}]'::jsonb),
  ('BOYS_BABIES', '[{"code":"FULL_ROMPERS_BOYS_NEW","title":"Combinaisons"},{"code":"BOYS_COMBI_PILOTES_NEW","title":"Combi-pilotes"},{"code":"KID_SLEEPSACK_BOYS_NEW","title":"Gigoteuses et turbulettes"},{"code":"BOYS_BODIES_NEW","title":"Bodies"},{"code":"ROMPERS_BOYS_NEW","title":"Grenouillères"},{"code":"BOYS_SETS_NEW","title":"Ensembles"},{"code":"OTHER_BABY_BOYS","title":"Autre"}]'::jsonb),
  ('BOYS_COATS', '[{"code":"BOYS_COATS_NEW","title":"Manteaux"},{"code":"BOYS_OUTVESTS_NEW","title":"Vestes sans manches"},{"code":"BOYS_JACKETS_NEW","title":"Vestes"},{"code":"BOYS_RAIN_GEAR","title":"Vêtements de pluie"},{"code":"BOYS_SNOW_GEAR","title":"Vêtements de ski"}]'::jsonb),
  ('BOYS_NEW', '[{"code":"BOYS_CLOTHING_BUNDLE","title":"Lot de vêtements"},{"code":"BOYS_BABIES","title":"Bébé garçons"},{"code":"BOYS_SHOES","title":"Chaussures"},{"code":"BOYS_COATS","title":"Vêtements d''extérieur"},{"code":"BOYS_SWEATERS","title":"Pulls & sweats"},{"code":"BOYS_SHIRTS","title":"Chemises et t-shirts"},{"code":"BOYS_PANTS","title":"Pantalons et shorts"},{"code":"BOYS_BAGS","title":"Sacs et sacs à dos"},{"code":"ACCESSORIES_BOYS_NEW","title":"Accessoires"},{"code":"BOYS_SWIM","title":"Équipements de natation"},{"code":"BOYS_SWIMWEAR","title":"Sous-vêtements"},{"code":"SLEEPWEAR_BOYS_NEW","title":"Pyjamas"},{"code":"BOYS_SPORTS","title":"Vêtements de sport"},{"code":"BOYS_PACKAGES","title":"Lots de vêtements"},{"code":"TWINS_BOYS_NEW","title":"Jumeaux et plus"},{"code":"OCC_BOYS_NEW","title":"Déguisements"},{"code":"BOYS_THEMED_COSTUMES","title":"Tenues de soirée"},{"code":"BOYS_OTHER","title":"Autres"}]'::jsonb),
  ('BOYS_PANTS', '[{"code":"JEANS_BOYS_NEW","title":"Jeans"},{"code":"SKINNYPANTS_BOYS_NEW","title":"Jeans slim"},{"code":"BELLBOTTOMPANTS_BOYS_NEW","title":"Pantalons pattes d''éléphant"},{"code":"BOYS_LEGGINGS_NEW","title":"Leggings"},{"code":"BOYS_JOGGINGS_NEW","title":"Joggings"},{"code":"OVERALLS_ROMPERS_BOYS_NEW","title":"Salopettes"},{"code":"BOYS_SHORTS","title":"Shorts et pantacourts"},{"code":"BOYS_PANTS_HAREM","title":"Sarouels"},{"code":"BOYS_OTH_PANTS","title":"Autres"}]'::jsonb),
  ('BOYS_SHIRTS', '[{"code":"TSHIRTS_BOYS_NEW","title":"T-shirts"},{"code":"POLOSHIRTS_BOYS_NEW","title":"Polos"},{"code":"SHIRTS_BOYS_NEW","title":"Chemises"},{"code":"SHORTSLEEVE_SHIRTS_BOYS_NEW","title":"Chemises manches courtes"},{"code":"LONGSLEEVE_BOYS_NEW","title":"Chemises manches longues"},{"code":"SLEEVELESS_SHIRTS_BOYS_NEW","title":"Chemises sans manches"},{"code":"OTHER_TOPS_BOYS","title":"Autre"}]'::jsonb),
  ('BOYS_SHOES', '[{"code":"BOY_BABYSHOES_NEW","title":"Chaussures bébé"},{"code":"BOYS_BOAT_LOAFERS_MOCCASINS","title":"Mocassins et chaussures bateau"},{"code":"BOOTS_BOYS_NEW","title":"Bottes"},{"code":"BOYS_ESPADRILLES","title":"Espadrilles"},{"code":"BOYS_FLIP_FLOPS_SANDALS_SLIDES","title":"Sandales, claquettes et tongs"},{"code":"SHOES_OCC_BOYS_NEW","title":"Chaussures habillées"},{"code":"SLIPPERS_BOYS_NEW","title":"Chaussons et pantoufles"},{"code":"BOYS_SPORT_SHOES","title":"Chaussures de sport"},{"code":"SNEAKERS_BOYS_NEW","title":"Baskets"}]'::jsonb),
  ('BOYS_SWEATERS', '[{"code":"SWEATERS_BOYS_NEW","title":"Pulls"},{"code":"VNECK_SWEATERS_BOYS_NEW","title":"Pulls col V"},{"code":"TURLENECK_BOYS_NEW","title":"Pulls à col roulé"},{"code":"ZIPP_SWEATERS_BOYS_NEW","title":"Gilets zippés"},{"code":"HOODIES_BOYS_NEW","title":"Pulls à capuche et sweatshirts"},{"code":"VESTS_BOYS_NEW","title":"Gilets"},{"code":"OTHER_SWEATERS_BOYS","title":"Autre"}]'::jsonb),
  ('BOYS_SWIM', '[{"code":"BATHSHORTS_BOYS_NEW","title":"Maillots de bain"},{"code":"BATHROBES_BOYS_NEW","title":"Peignoirs"}]'::jsonb),
  ('BOYS_SWIMWEAR', '[{"code":"SOCKS_BOYS_NEW","title":"Chaussettes"},{"code":"TIGHTS_BOYS_NEW","title":"Collants"},{"code":"PANTIES_BOYS_NEW","title":"Culottes"},{"code":"OTHER_UNDER_BOYS","title":"Autre"}]'::jsonb),
  ('BREASTFEEDING', '[{"code":"BREASTPUMPS","title":"Tire-lait"},{"code":"BREASTPUMP_ACC","title":"Accessoires pour tire-lait"},{"code":"BREASTFEEDING_COVER","title":"Couvertures d''allaitement"},{"code":"NIPPLE_SHIELD","title":"Coussinets d''allaitement et protège-mamelon"}]'::jsonb),
  ('CARTES_A_COLLECTIONNER', '[{"code":"CARTE_A_L_UNITE","title":"Carte à l''unité"},{"code":"LOT_DE_CARTES","title":"Lot de cartes"},{"code":"BOOSTER","title":"Booster"}]'::jsonb),
  ('CHANGING_MATSANDCOVERS', '[{"code":"CHANGING_MATS","title":"Matelas à langer"},{"code":"CHANGING_MAT_COVER","title":"Housses de matelas à langer"},{"code":"CHANGING_MAT_PORTABLE","title":"Matelas à langer nomades"}]'::jsonb),
  ('CHILDREN_NEW', '[{"code":"GIRLS_NEW","title":"Vêtements pour filles"},{"code":"BOYS_NEW","title":"Vêtements pour garçons"},{"code":"KID_BATHING_CHANGING","title":"Bain et change"},{"code":"NURSING_FEEDING","title":"Allaitement et alimentation"},{"code":"KID_SLEEP_BEDDING","title":"Sommeil et literie"},{"code":"KID_SCHOOL_SUPPLIES","title":"Affaires scolaires"},{"code":"ALL_OTHER_NEW","title":"Autres articles pour bébé et enfant"},{"code":"BABY_CARRIERS","title":"Portage bébé"},{"code":"BABY_ACCESSORIES","title":"Accessoires bébé"},{"code":"BABY_ROOM_DECOR","title":"Décoration chambre"}]'::jsonb),
  ('COATS_JACKETS', '[{"code":"CAPES_PONCHOS","title":"Capes et ponchos"},{"code":"W_COATS","title":"Manteaux"},{"code":"WOMEN_OUTERWEAR_VESTS","title":"Vestes sans manches"},{"code":"W_JACKETS","title":"Vestes"},{"code":"W_BOMBERS","title":"Blousons mi-saison"},{"code":"W_RAINCOATS","title":"Imperméables et coupe-vent"}]'::jsonb),
  ('COLLECTION', '[{"code":"HC_MEMORABILIA_SPORTS","title":"Souvenirs de sport"},{"code":"HC_MEMORABILIA_MUSIC","title":"Souvenirs de musique"},{"code":"HC_MEMORABILIA_FILMTV","title":"Souvenirs TV et cinéma"},{"code":"HC_MEMORABILIA_OTHER","title":"Autres souvenirs"},{"code":"HC_NUMISMATICS_BANKNOTES","title":"Billets"},{"code":"HC_NUMISMATICS_COINS","title":"Pièces de monnaie"},{"code":"HC_NUMISMATICS_LOTS","title":"Lots de monnaies"},{"code":"HC_NUMISMATICS_MEDALSTOKENS","title":"Médailles et jetons"},{"code":"HC_NUMISMATICS_SHARES","title":"Titres et actions"},{"code":"HC_PHILATELY_SINGLES","title":"Timbres à l''unité"},{"code":"HC_PHILATELY_LOTS","title":"Lots de timbres"},{"code":"HC_PHILATELY_FDC","title":"Enveloppes premier jour"},{"code":"HC_PHILATELY_GUIDES","title":"Catalogues et guides de timbres"},{"code":"HC_PHILATELY_TOOLS","title":"Outils et matériel pour timbres"},{"code":"HC_POSTCARDS","title":"Cartes postales"}]'::jsonb),
  ('COLLECTION_STORAGE', '[{"code":"HC_STORAGE_ALBUMS","title":"Albums et classeurs"},{"code":"HC_STORAGE_BOXES","title":"Boîtes de rangement"},{"code":"HC_STORAGE_SLEEVES","title":"Protège-cartes souples"},{"code":"HC_STORAGE_SCREWDOWNS","title":"Protège-cartes rigides"},{"code":"HC_STORAGE_DECKBOXES","title":"Boîtes pour jeux de cartes"},{"code":"HC_STORAGE_ALBUMDIVIDERS","title":"Intercalaires"},{"code":"HC_STORAGE_ALBUMREFILLS","title":"Recharges pour albums"},{"code":"HC_STORAGE_PUZZLEMATS","title":"Tapis de puzzle"},{"code":"HC_STORAGE_OTHER","title":"Autres rangements"},{"code":"HC_GAMING_ACC_DICE","title":"Dés"},{"code":"HC_GAMING_ACC_TOKENS","title":"Jetons et marqueurs"},{"code":"HC_GAMING_ACC_PLAYMATS","title":"Tapis de jeu"},{"code":"HC_GAMING_ACC_OTHER","title":"Autres accessoires de jeux"}]'::jsonb),
  ('CONSOLES', '[{"code":"CONSOLES_PORTABLES","title":"Consoles portables"},{"code":"CONSOLES_DE_SALON","title":"Consoles de salon"}]'::jsonb),
  ('CULTURE_ET_LOISIR', '[{"code":"LIVRES","title":"Livres"},{"code":"MUSIQUE","title":"Musique"},{"code":"VIDEO","title":"Vidéo"},{"code":"CARTES_A_COLLECTIONNER","title":"Cartes à collectionner"},{"code":"CONSOLES","title":"Consoles"},{"code":"JEUX_VIDEO","title":"Jeux vidéo"},{"code":"ORDINATEURS_ACCESSOIRES","title":"High-tech et accessoires"},{"code":"LOISIRS_CREATIFS","title":"Loisirs créatifs et couture"},{"code":"COLLECTION","title":"Collection"},{"code":"COLLECTION_STORAGE","title":"Rangement de collection"}]'::jsonb),
  ('DOLLS_NEW', '[{"code":"DOLLS","title":"Poupées et poupons"},{"code":"DOLL_CLOTHES_ACC","title":"Accessoires pour poupée et poupon"},{"code":"DOLL_FURNITURE","title":"Meubles et accessoires pour maison de poupée"},{"code":"DOLLHOUSE","title":"Maisons de poupées"},{"code":"DOLL_PLAYSET","title":"Kits de jeu pour poupée et poupon"}]'::jsonb),
  ('DRESSES', '[{"code":"MAXI_DRESSES","title":"Robes longues"},{"code":"OCCASIONAL_DRESSES","title":"Robes pour occasions"},{"code":"SUMMER_DRESSES","title":"Robes d''été"},{"code":"WINTER_DRESSES","title":"Robes d''hiver"},{"code":"FORMAL_DRESSES","title":"Robes chics"},{"code":"CASUAL_DRESSES","title":"Robes casual"},{"code":"STRAPLESS_DRESSES","title":"Robes sans bretelles"},{"code":"LITTLE_BLACK_DRESSES","title":"Petites robes noires"},{"code":"JEANS_DRESSES_TUNICS","title":"Robes en jean"},{"code":"WOM_DRE_OTHER","title":"Autres robes"}]'::jsonb),
  ('EDUCATIONAL_TOYS_NEW', '[{"code":"FLASH_CARDS","title":"Cartes flash"},{"code":"PRISM_TOYS","title":"Kaléidoscopes et prismes"},{"code":"PHONICS_TOYS","title":"Jeux de lecture et d''écriture"},{"code":"STEM_TOYS","title":"Jeux scientifiques et STEM"},{"code":"OTHER_EDU_TOYS","title":"Autres jeux éducatifs"}]'::jsonb),
  ('ELECTRONIC_NEW', '[{"code":"AUDIOPLAYER_MEDIA","title":"Musiques et histoires"},{"code":"ELEC_PET","title":"Peluches interactives"},{"code":"KARAOKE_TOY","title":"Équipements de karaoké pour enfants"},{"code":"AUDIOPLAYER_TOY","title":"Boîtes à musique et histoires"},{"code":"RC_TOY","title":"Jouets télécommandés"},{"code":"KID_CAMERA","title":"Appareils photo pour enfant"},{"code":"WALKIE_TALKIE_TOY","title":"Talkies-walkies"},{"code":"OTHER_ELEC_TOY","title":"Autres jeux et jouets électroniques"}]'::jsonb),
  ('FAIT_MAIN', '[{"code":"FAIT_MAIN_BIJOUX","title":"Bijoux (fait main)"},{"code":"FAIT_MAIN_VETEMENTS","title":"Vêtements & accessoires (fait main)"},{"code":"FAIT_MAIN_MAISON_DECO","title":"Maison & déco (fait main)"},{"code":"FAIT_MAIN_PAPETERIE","title":"Papeterie & cartes (fait main)"},{"code":"FAIT_MAIN_BOIS","title":"Bois & gravure (fait main)"}]'::jsonb),
  ('FOOTWEAR', '[{"code":"WOMEN_BALLERINAS","title":"Ballerines"},{"code":"WOMEN_BOAT_SHOES_LOAFERS_MOCCASINS","title":"Mocassins et chaussures bateau"},{"code":"W_BOOTS","title":"Bottes"},{"code":"WOMEN_CLOGS_MULES","title":"Mules et sabots"},{"code":"WOMEN_ESPADRILLES","title":"Espadrilles"},{"code":"WOMEN_FLIPFLOPS_SLIDES","title":"Claquettes et tongs"},{"code":"HIGH_HEELS","title":"Chaussures à talons"},{"code":"WOMEN_LACE_UP_SHOES","title":"Chaussures à lacets"},{"code":"WOMEN_SANDALS","title":"Sandales"},{"code":"SLIPPERS","title":"Chaussons et pantoufles"},{"code":"WOMEN_SPORT_SHOES","title":"Chaussures de sport"},{"code":"WOMEN_TRAINERS","title":"Baskets"}]'::jsonb),
  ('GIRLS_BABIES', '[{"code":"FULL_ROMPERS_GIRLS_NEW","title":"Combinaisons"},{"code":"GIRLS_COMBI_PILOTES_NEW","title":"Combi-pilotes"},{"code":"KID_SLEEPSACK","title":"Gigoteuses et turbulettes"},{"code":"GIRLS_BODIES_NEW","title":"Bodies"},{"code":"ROMPERS_GIRLS_NEW","title":"Grenouillères"},{"code":"SETS_GIRLS_NEW","title":"Ensembles"},{"code":"GIRLS_BABIES_OTHERS","title":"Autre"}]'::jsonb),
  ('GIRLS_COATS', '[{"code":"COATS_GIRLS_NEW","title":"Manteaux"},{"code":"OUT_VESTS_GIRLS_NEW","title":"Vestes sans manches"},{"code":"JACKETS_GIRLS_NEW","title":"Vestes"},{"code":"GIRLS_RAIN_GEAR","title":"Vêtements de pluie"},{"code":"GIRLS_SNOW_GEAR","title":"Vêtements de ski"}]'::jsonb),
  ('GIRLS_DRESSES', '[{"code":"SHORTDRESSES_GIRLS_NEW","title":"Robes courtes"},{"code":"LONGDRESSES_GIRLS_NEW","title":"Robes longues"}]'::jsonb),
  ('GIRLS_NEW', '[{"code":"GIRLS_CLOTHING_BUNDLE","title":"Lot de vêtements"},{"code":"GIRLS_BABIES","title":"Bébé filles"},{"code":"GIRLS_SHOES","title":"Chaussures"},{"code":"GIRLS_COATS","title":"Vêtements d''extérieur"},{"code":"GIRLS_SWEATERS","title":"Pulls & sweats"},{"code":"GIRLS_SHIRTS","title":"Chemises et t-shirts"},{"code":"GIRLS_DRESSES","title":"Robes"},{"code":"GIRLS_SKIRTS","title":"Jupes"},{"code":"GIRLS_PANTS","title":"Pantalons et shorts"},{"code":"GIRLS_BAGS","title":"Sacs et sacs à dos"},{"code":"ACCESSORIES_GIRLS_NEW","title":"Accessoires"},{"code":"GIRLS_SWIM","title":"Équipements de natation"},{"code":"GIRLS_UNDERW","title":"Sous-vêtements"},{"code":"SLEEPWEAR_GIRLS_NEW","title":"Pyjamas et chemises de nuit"},{"code":"GIRLS_SPORTS","title":"Vêtements de sport"},{"code":"CLOTHING_PACKAGES_NEW","title":"Lots de vêtements"},{"code":"COSTUMES_GIRLS_NEW","title":"Déguisements"},{"code":"THEMED_COSTUMES_NEW","title":"Tenues de soirée"},{"code":"GIRLS_OTHER","title":"Autres"}]'::jsonb),
  ('GIRLS_PANTS', '[{"code":"JEANS_GIRLS_NEW","title":"Jeans"},{"code":"SKINNYPANTS_GIRLS_NEW","title":"Jeans slim"},{"code":"BELLBOTTOMPANTS_GIRLS_NEW","title":"Pantalons pattes d''éléphant"},{"code":"LEGGINGS_GIRLS_NEW","title":"Leggings"},{"code":"JOGGINGS_GIRLS_NEW","title":"Joggings"},{"code":"OVERALLS_ROMPERS_GIRLS_NEW","title":"Salopettes"},{"code":"GIRLS_SHORTS","title":"Shorts et pantacourts"},{"code":"HAREM_GIRLS_NEW","title":"Sarouels"},{"code":"OTHER_PANTS_GIRLS","title":"Autres"}]'::jsonb),
  ('GIRLS_SHIRTS', '[{"code":"TOPS_GIRLS_NEW","title":"T-shirts"},{"code":"POLOSHIRTS_GIRLS_NEW","title":"Polos"},{"code":"SHIRTS_GIRLS_NEW","title":"Chemises"},{"code":"SHORTSLEEVE_SHIRTS_GIRLS_NEW","title":"Chemises manches courtes"},{"code":"LOGSLEEVE_SHIRTS_GIRLS_NEW","title":"Chemises manches longues"},{"code":"SLEEVELESS_SHIRTS_GIRLS_NEW","title":"Chemises sans manches"},{"code":"TUNICS_GIRLS_NEW","title":"Tuniques ou blouses"},{"code":"OTHER_TOPS_GIRLS","title":"Autre"}]'::jsonb)
)
insert into public.platform_category_aspects
  (platform, category_key, field_key, field_label, required, input_type, allowed_values, source)
select 'opla', category_key, 'category', 'Catégorie', true, 'select', allowed_values, 'manual'
  from niveaux
on conflict (platform, category_key, field_key) do update
  set allowed_values = excluded.allowed_values,
      field_label    = excluded.field_label,
      input_type     = excluded.input_type,
      required       = excluded.required,
      source         = excluded.source,
      last_seen_at   = now();


-- niveaux de choix 46 à 90 sur 129
with niveaux (category_key, allowed_values) as (values
  ('GIRLS_SHOES', '[{"code":"BABY_GIRLS_SHOES_NEW","title":"Chaussures bébé"},{"code":"BOOTS_GIRLS_NEW","title":"Bottes"},{"code":"FLAT_GIRLS_NEW","title":"Chaussures plates"},{"code":"GIRLS_FLIP_FLOPS_SANDALS_SLIDES","title":"Sandales, claquettes et tongs"},{"code":"SHOES_OCC_GIRLS_NEW","title":"Chaussures habillées"},{"code":"GIRLS_HEELS","title":"Chaussures à talons"},{"code":"SLIPPERS_GIRLS_NEW","title":"Chaussons et pantoufles"},{"code":"GIRLS_SPORT_SHOES","title":"Chaussures de sport"},{"code":"SNEAKERS_GIRLS_NEW","title":"Baskets"}]'::jsonb),
  ('GIRLS_SWEATERS', '[{"code":"SWEATERS_GIRLS_NEW","title":"Pulls"},{"code":"VNECK_SWEATERS_GIRLS_NEW","title":"Pulls col V"},{"code":"TURLENECK_GRILS_NEW","title":"Pulls à col roulé"},{"code":"ZIPP_SWEATERS_GIRLS_NEW","title":"Gilets zippés"},{"code":"BOLEROS_GIRLS_NEW","title":"Boléros"},{"code":"HOODIES_GIRLS_NEW","title":"Pulls à capuche & sweatshirts"},{"code":"VESTS_GIRLS_NEW","title":"Gilets"},{"code":"OTHER_SWEATERS_GIRLS","title":"Autre"}]'::jsonb),
  ('GIRLS_SWIM', '[{"code":"SWIMSUITS_GIRLS_NEW","title":"Maillot de bain 1 pièce"},{"code":"BIKINIS_GIRLS_NEW","title":"Maillot de bain 2 pièces"},{"code":"BATHROBES_GIRLS_NEW","title":"Peignoirs"}]'::jsonb),
  ('GIRLS_UNDERW', '[{"code":"SOCKS_GIRLS_NEW","title":"Chaussettes"},{"code":"TIGHTS_GIRLS_NEW","title":"Collants"},{"code":"PANTIES_GIRLS_NEW","title":"Culottes"}]'::jsonb),
  ('HATS_CAPS', '[{"code":"MEN_BALACLAVAS","title":"Cagoules"},{"code":"MEN_BEANIES","title":"Bonnets"},{"code":"MEN_ACC_HAT_CAPS","title":"Casquettes"},{"code":"MEN_ACC_HAT_HATS","title":"Chapeaux"}]'::jsonb),
  ('JEANS', '[{"code":"W_CROPPED_JEANS","title":"Jeans courts"},{"code":"FLARED_JEANS","title":"Jeans évasés"},{"code":"W_HIGH_WAIST_JEANS","title":"Jeans taille haute"},{"code":"W_RIPPED_JEANS","title":"Jeans troués"},{"code":"W_SKINNY_JEANS","title":"Jeans skinny"},{"code":"W_STRAIGHT_JEANS","title":"Jeans droits"},{"code":"JEANS_OTHER","title":"Autre"}]'::jsonb),
  ('JEUX_VIDEO', '[{"code":"JEUX_VIDEO_PLAYSTATION","title":"Jeux PlayStation"},{"code":"JEUX_VIDEO_XBOX","title":"Jeux Xbox"},{"code":"JEUX_VIDEO_NINTENDO","title":"Jeux Nintendo"},{"code":"JEUX_VIDEO_PC","title":"Jeux PC"},{"code":"JEUX_VIDEO_RETRO","title":"Jeux rétro"}]'::jsonb),
  ('JEWELRY', '[{"code":"ANKLETS_NEW","title":"Bracelets de cheville"},{"code":"WOMEN_BODY_JEWELLERY","title":"Bijoux de corps"},{"code":"BRACELETS","title":"Bracelets"},{"code":"BROOCHES","title":"Broches"},{"code":"WOMEN_CHARMS_PENDANTS","title":"Breloques et pendentifs"},{"code":"EARRINGS","title":"Boucles d''oreilles"},{"code":"WOM_ACC_JEW_SETS","title":"Ensembles de bijoux"},{"code":"NECKLACES_BEADS_PENDANTS","title":"Colliers"},{"code":"WOM_ACC_JEW_RINGS","title":"Bagues"},{"code":"WOM_ACC_JEW_OTHER","title":"Autres bijoux"}]'::jsonb),
  ('JEWELRY_GIRLS_NEW', '[{"code":"BRACELETS_GIRLS_NEW","title":"Bracelets"},{"code":"EARRINGS_GIRLS_NEW","title":"Boucles d''oreilles"},{"code":"NECKLACES_GIRLS_NEW","title":"Colliers"},{"code":"RINGS_GIRLS_NEW","title":"Bagues"},{"code":"JEW_SETS_GIRLS_NEW","title":"Ensembles de bijoux"},{"code":"CHARMS_GIRLS_NEW","title":"Breloques et pendentifs"},{"code":"JEW_OTHER_GIRLS_NEW","title":"Autres bijoux"}]'::jsonb),
  ('JUMPSUITS_UK', '[{"code":"W_JUMPSUITS","title":"Combinaisons"},{"code":"W_ROMPERS","title":"Combi Shorts"},{"code":"W_OTHER_ROMPERS_JUMPSUITS","title":"Autres combinaisons & combishorts"}]'::jsonb),
  ('KID_BATHING', '[{"code":"BABY_BATHTUB","title":"Baignoires et sièges de bain"},{"code":"BABY_BATH_ACC","title":"Accessoires de bain"},{"code":"BABY_BATH_TOWEL","title":"Serviettes de bain"}]'::jsonb),
  ('KID_BATHING_CHANGING', '[{"code":"KID_CHANGING_BAG","title":"Sacs à langer"},{"code":"KID_BATHING","title":"Bain"},{"code":"CHANGING_MATSANDCOVERS","title":"Matelas à langer et housses"},{"code":"BABY_POTTIES","title":"Pots et réducteurs"},{"code":"KID_STEPSTOOL","title":"Marchepieds"}]'::jsonb),
  ('KID_BEDDING', '[{"code":"KID_BLANKETS","title":"Couvertures et plaids"},{"code":"KID_MATTRESS_COVER","title":"Draps-housses et alèses"},{"code":"KID_PILLOW","title":"Oreillers"},{"code":"KID_SHEETS","title":"Draps"}]'::jsonb),
  ('KID_CRAFTS', '[{"code":"KID_SMOCKS","title":"Tabliers et blouses"},{"code":"KID_BEADS","title":"Perles et fabrication de bijoux"},{"code":"KID_CLAY","title":"Argile et pâte à modeler"},{"code":"KID_CRAFT_KIT","title":"Kits créatifs"},{"code":"KID_DRAW_PAINT","title":"Peinture et dessin"},{"code":"KID_EASELS","title":"Tableaux et ardoises"},{"code":"KID_PRINT_STAMP","title":"Pochoirs et tampons"},{"code":"KID_STICKER_STATIONERY","title":"Gommettes et accessoires de papeterie"}]'::jsonb),
  ('KID_SCHOOL_SUPPLIES', '[{"code":"KID_SCHOOL_BAGS","title":"Cartables et sacs à dos"},{"code":"KID_SCHOOL_PENCIL_CASES","title":"Trousses"},{"code":"KID_SCHOOL_SUPPLIES_GENERAL","title":"Fournitures scolaires"},{"code":"KID_SCHOOL_CALCULATORS_GEOMETRY","title":"Calculatrices et matériel de géométrie"},{"code":"KID_SCHOOL_LUNCH","title":"Boîtes à goûter et gourdes"}]'::jsonb),
  ('KID_SLEEP_BEDDING', '[{"code":"KID_BABY_MONITOR","title":"Babyphones"},{"code":"KID_BEDDING","title":"Linge de lit, couvertures et plaids"},{"code":"KID_HEATINGPADS","title":"Coussins chauffants et bouillottes"},{"code":"KIDS_NIGHT_LIGHTS","title":"Veilleuses"},{"code":"KID_SLEEPINGBAG","title":"Sacs de couchage"},{"code":"KID_SWADDLE","title":"Couvertures d''emmaillotage"},{"code":"KID_WHITENOISE_MACHINE","title":"Générateurs de bruits blancs"}]'::jsonb),
  ('LINGERIE', '[{"code":"BRAS","title":"Soutiens-gorge"},{"code":"PANTIES_THONGS","title":"Culottes"},{"code":"WOM_LIN_SETS","title":"Ensembles"},{"code":"NIGHTWEAR","title":"Pyjamas et tenues de nuit"},{"code":"DRESSING_GOWNS","title":"Peignoirs"},{"code":"INTIMATES_TIGHTS","title":"Collants"},{"code":"INTIMATES_SOCKS","title":"Chaussettes"},{"code":"LINGERIE_ACC","title":"Accessoires de lingerie"},{"code":"WOM_LIN_OTHER","title":"Autres"}]'::jsonb),
  ('LIVRES', '[{"code":"LIVRES_POUR_BEBE","title":"Livres pour bébé"},{"code":"LIVRES_SONORES","title":"Livres sonores"},{"code":"ROMANS_POUR_ENFANTS","title":"Romans pour enfants"},{"code":"BANDES_DESSINEES","title":"Bandes dessinées"},{"code":"ROMANS_POUR_ADULTES","title":"Romans pour adultes"},{"code":"MANGAS","title":"Mangas"},{"code":"MANUELS_SCOLAIRES","title":"Manuels scolaires"},{"code":"FICTIONS","title":"Fictions"},{"code":"NON_FICTION","title":"Non-fiction"},{"code":"LIVRES_CUISINE","title":"Cuisine"},{"code":"LIVRES_MAGAZINES","title":"Magazines et revues"}]'::jsonb),
  ('LOISIRS_CREATIFS', '[{"code":"LOISIRS_COUTURE","title":"Couture et mercerie"},{"code":"LOISIRS_TRICOT_CROCHET","title":"Tricot et crochet"},{"code":"LOISIRS_PEINTURE_DESSIN","title":"Peinture et dessin"},{"code":"LOISIRS_BRODERIE","title":"Broderie et point de croix"},{"code":"LOISIRS_SCRAPBOOKING","title":"Scrapbooking et papeterie créative"},{"code":"LOISIRS_BIJOUX_DIY","title":"Bijoux DIY"},{"code":"LOISIRS_MODELISME","title":"Modélisme et maquettes"},{"code":"LOISIRS_CREATIFS_ENFANTS","title":"Loisirs créatifs enfants"},{"code":"LOISIRS_FILAMENT_3D","title":"Filament pour impression 3D"},{"code":"LOISIRS_AUTRES","title":"Autres loisirs créatifs"}]'::jsonb),
  ('MAISON', '[{"code":"MAISON_DECORATION","title":"Décoration"},{"code":"MAISON_TABLEWARE","title":"Arts de la table"},{"code":"MAISON_TEXTILES","title":"Textiles"},{"code":"MAISON_PETS","title":"Animaux"},{"code":"MAISON_PARTY","title":"Célébrations et fêtes"},{"code":"MAISON_DIY","title":"Outils et bricolage"},{"code":"MAISON_KITCHEN_TOOLS","title":"Outils de cuisine"},{"code":"MAISON_SMALL_APPLIANCES","title":"Petits appareils de cuisine"},{"code":"MAISON_OFFICE","title":"Fournitures de bureau"},{"code":"MAISON_BAKING","title":"Cuisson et pâtisserie"},{"code":"MAISON_OUTDOOR","title":"Extérieur et jardin"},{"code":"MAISON_MAINTENANCE","title":"Entretien de la maison"}]'::jsonb),
  ('MAISON_BAKING', '[{"code":"MAISON_BAKING_ACCESSORIES","title":"Accessoires pour la cuisine et la pâtisserie"},{"code":"MAISON_BAKING_MOLDS","title":"Moules de cuisson"},{"code":"MAISON_BAKING_SPECIALTY","title":"Matériel de cuisson et de pâtisserie spécialisé"},{"code":"MAISON_BAKING_POTS","title":"Casseroles"},{"code":"MAISON_BAKING_OVEN_DISHES","title":"Plats pour le four"},{"code":"MAISON_BAKING_PANS","title":"Poêles"}]'::jsonb),
  ('MAISON_DECORATION', '[{"code":"MAISON_DECO_ACCESSORIES","title":"Accessoires décoratifs"},{"code":"MAISON_DECO_STORAGE","title":"Rangement et organisation"},{"code":"MAISON_DECO_WALL_ART","title":"Décorations murales"},{"code":"MAISON_DECO_CANDLES","title":"Bougies et parfums d''ambiance"},{"code":"MAISON_DECO_LIGHTING","title":"Éclairage"},{"code":"MAISON_DECO_SCULPTURES","title":"Sculptures et figurines"},{"code":"MAISON_DECO_FRAMES","title":"Encadrements"},{"code":"MAISON_DECO_VASES","title":"Vases"},{"code":"MAISON_DECO_SHELVES","title":"Étagères murales"},{"code":"MAISON_DECO_CLOCKS","title":"Horloges"},{"code":"MAISON_DECO_ARTIFICIAL_PLANTS","title":"Plantes et fleurs artificielles"},{"code":"MAISON_DECO_MIRRORS","title":"Miroirs"},{"code":"MAISON_DECO_FIREPLACE","title":"Accessoires pour cheminées"}]'::jsonb),
  ('MAISON_DIY', '[{"code":"MAISON_DIY_HARDWARE","title":"Quincaillerie"},{"code":"MAISON_DIY_SMART_HOME","title":"Maisons connectées et sécurité"},{"code":"MAISON_DIY_PROTECTION","title":"Équipement de protection"},{"code":"MAISON_DIY_HAND_TOOLS","title":"Outils à main"},{"code":"MAISON_DIY_POWER_TOOLS","title":"Outils électriques"},{"code":"MAISON_DIY_TOOL_ACCESSORIES","title":"Accessoires pour outils"},{"code":"MAISON_DIY_PAINT_TOOLS","title":"Outils et accessoires de peinture"},{"code":"MAISON_DIY_TOOL_STORAGE","title":"Transport et rangement des outils"},{"code":"MAISON_DIY_MEASURING","title":"Outils de mesure"},{"code":"MAISON_DIY_PLUMBING","title":"Outils de plomberie"},{"code":"MAISON_DIY_WORKSHOP","title":"Équipement d''atelier et de chantier"},{"code":"MAISON_DIY_ELECTRICAL","title":"Outils d''électricien"},{"code":"MAISON_DIY_MASONRY","title":"Outils de maçonnerie"}]'::jsonb),
  ('MAISON_KITCHEN_TOOLS', '[{"code":"MAISON_KT_FOOD_STORAGE","title":"Stockage alimentaire"},{"code":"MAISON_KT_UTENSILS","title":"Ustensiles de cuisine"},{"code":"MAISON_KT_SPECIALTY_UTENSILS","title":"Ustensiles de cuisine spécialisés"},{"code":"MAISON_KT_BAR","title":"Accessoires de bar"},{"code":"MAISON_KT_MIXING_BOWLS","title":"Bols à mélanger"},{"code":"MAISON_KT_STRAINERS","title":"Passoires, tamis et chinois"},{"code":"MAISON_KT_CUTTING_BOARDS","title":"Planches à découper"},{"code":"MAISON_KT_MEASURING","title":"Tasses et cuillères à mesurer"},{"code":"MAISON_KT_SCALES","title":"Balances de cuisine"},{"code":"MAISON_KT_THERMOMETERS","title":"Thermomètres alimentaires"}]'::jsonb),
  ('MAISON_MAINTENANCE', '[{"code":"MAISON_MAINT_VACUUMS","title":"Aspirateurs et nettoyage"},{"code":"MAISON_MAINT_HEATING","title":"Chauffage, climatisation et ventilation"},{"code":"MAISON_MAINT_IRONS","title":"Fers à repasser et entretien du linge"}]'::jsonb),
  ('MAISON_OFFICE', '[{"code":"MAISON_OFFICE_WRITING","title":"Fournitures d''écriture"},{"code":"MAISON_OFFICE_PLANNERS","title":"Agendas et organiseurs"},{"code":"MAISON_OFFICE_PENCIL_CASES","title":"Trousses"},{"code":"MAISON_OFFICE_NOTEBOOKS","title":"Carnets et blocs-notes"},{"code":"MAISON_OFFICE_ACCESSORIES","title":"Accessoires de bureau"},{"code":"MAISON_OFFICE_ELECTRONICS","title":"Matériel électronique de bureau"},{"code":"MAISON_OFFICE_CALCULATORS","title":"Calculatrices"},{"code":"MAISON_OFFICE_BOOKMARKS","title":"Marque-pages"},{"code":"MAISON_OFFICE_DOC_ORG","title":"Organiseurs de documents"},{"code":"MAISON_OFFICE_TAPE","title":"Rubans adhésifs, pinces et attaches"},{"code":"MAISON_OFFICE_STAPLERS","title":"Agrafeuses et perforatrices"},{"code":"MAISON_OFFICE_DRAWING","title":"Outils de dessin technique"},{"code":"MAISON_OFFICE_PRESENTATION","title":"Matériel de présentation"}]'::jsonb),
  ('MAISON_OUTDOOR', '[{"code":"MAISON_OUTDOOR_POTS","title":"Pots, jardinières et accessoires"},{"code":"MAISON_OUTDOOR_GARDEN_DECO","title":"Décorations de jardin et d''extérieur"},{"code":"MAISON_OUTDOOR_POWER_ACCESSORIES","title":"Accessoires pour outils électriques d''extérieur"},{"code":"MAISON_OUTDOOR_POOLS","title":"Spas, piscines et équipements"},{"code":"MAISON_OUTDOOR_WATERING","title":"Équipement d''arrosage"},{"code":"MAISON_OUTDOOR_HAND_TOOLS","title":"Outils manuels de jardin"},{"code":"MAISON_OUTDOOR_GRILLING","title":"Cuisine et grillade d''extérieur"},{"code":"MAISON_OUTDOOR_POWER_TOOLS","title":"Outils électriques d''extérieur"},{"code":"MAISON_OUTDOOR_WEATHER","title":"Instruments météorologiques"},{"code":"MAISON_OUTDOOR_SNOW_TOOLS","title":"Outils de déneigement"}]'::jsonb),
  ('MAISON_PARTY', '[{"code":"MAISON_PARTY_SEASONAL","title":"Décorations saisonnières"},{"code":"MAISON_PARTY_TABLE_DECO","title":"Décorations de table"},{"code":"MAISON_PARTY_ACCESSORIES","title":"Accessoires de fête"},{"code":"MAISON_PARTY_TREE_DECO","title":"Décorations pour le sapin"},{"code":"MAISON_PARTY_CARDS","title":"Cartes et enveloppes"},{"code":"MAISON_PARTY_GIFT_WRAP","title":"Papier cadeau et sacs"},{"code":"MAISON_PARTY_BANNERS","title":"Banderoles, drapeaux et guirlandes"},{"code":"MAISON_PARTY_WREATHS","title":"Couronnes"}]'::jsonb),
  ('MAISON_PETS', '[{"code":"MAISON_PETS_DOGS","title":"Chiens"},{"code":"MAISON_PETS_CATS","title":"Chats"},{"code":"MAISON_PETS_REPTILES","title":"Reptiles"},{"code":"MAISON_PETS_BIRDS","title":"Oiseaux"},{"code":"MAISON_PETS_RODENTS","title":"Rongeurs & co"},{"code":"MAISON_PETS_FISH","title":"Poissons"}]'::jsonb),
  ('MAISON_SMALL_APPLIANCES', '[{"code":"MAISON_SA_COFFEE","title":"Préparation du café, du thé et de l''expresso"},{"code":"MAISON_SA_BLENDERS","title":"Blenders, mixeurs et robots de cuisine"},{"code":"MAISON_SA_SPECIALTY","title":"Appareils spécialisés"},{"code":"MAISON_SA_ACCESSORIES","title":"Accessoires pour petits appareils de cuisine"},{"code":"MAISON_SA_FRYERS","title":"Friteuses"},{"code":"MAISON_SA_GRILLS","title":"Grils et planchas"},{"code":"MAISON_SA_JUICERS","title":"Extracteurs de jus"},{"code":"MAISON_SA_SPARE_PARTS","title":"Pièces détachées pour petits appareils de cuisine"},{"code":"MAISON_SA_KETTLES","title":"Bouilloires"},{"code":"MAISON_SA_TOASTERS","title":"Grille-pain"},{"code":"MAISON_SA_WATER_DISPENSERS","title":"Distributeurs d''eau et de boissons"}]'::jsonb),
  ('MAISON_TABLEWARE', '[{"code":"MAISON_TABLE_DRINKWARE","title":"Verres"},{"code":"MAISON_TABLE_SERVEWARE","title":"Vaisselle de service"},{"code":"MAISON_TABLE_DINNERWARE","title":"Vaisselle"},{"code":"MAISON_TABLE_CUTLERY","title":"Couverts"}]'::jsonb),
  ('MAISON_TEXTILES', '[{"code":"MAISON_TEXTILE_BEDDING","title":"Linge de lit"},{"code":"MAISON_TEXTILE_TABLE_LINEN","title":"Linge de table"},{"code":"MAISON_TEXTILE_CUSHIONS","title":"Coussins décoratifs"},{"code":"MAISON_TEXTILE_CURTAINS","title":"Rideaux et stores"},{"code":"MAISON_TEXTILE_TOWELS","title":"Serviettes"},{"code":"MAISON_TEXTILE_BLANKETS","title":"Couvertures"},{"code":"MAISON_TEXTILE_RUGS","title":"Tapis"},{"code":"MAISON_TEXTILE_COVERS","title":"Housses"},{"code":"MAISON_TEXTILE_TAPESTRIES","title":"Tapisseries"}]'::jsonb),
  ('MATERNITY_CLOTHES_MAIN', '[{"code":"MATERNITY_TOPS","title":"Tops maternité"},{"code":"MATERNITY_DRESSES","title":"Robes maternité"},{"code":"MATERNITY_SKIRTS","title":"Jupes maternité"},{"code":"MATERNITY_PANTS","title":"Pantalons maternité"},{"code":"MATERNITY_SHORTS","title":"Shorts maternité"},{"code":"MATERNITY_ROMPERS_JUMPSUITS","title":"Combinaisons & combi shorts maternité"},{"code":"MATERNITY_HOODIES_SWEATERS","title":"Pulls à capuche & pulls maternité"},{"code":"MATERNITY_COATS_JACKETS","title":"Manteaux & vestes maternité"},{"code":"MATERNITY_SWIMWEAR_BEACHWEAR","title":"Maillots & tenues de plage maternité"},{"code":"MATERNITY_UNDERWEAR","title":"Sous-vêtements maternité"},{"code":"MATERNITY_SPORT","title":"Vêtements de sport"}]'::jsonb),
  ('MENS', '[{"code":"MEN_CLOTHING","title":"Vêtements"},{"code":"MEN_SHOES_NEW","title":"Chaussures"},{"code":"MEN_ACCESSORIES","title":"Accessoires"}]'::jsonb),
  ('MEN_ACCESSORIES', '[{"code":"BAGS","title":"Sacs et sacoches"},{"code":"MEN_BANDANAS_HEADSCARVES","title":"Bandanas et foulards pour cheveux"},{"code":"MEN_ACC_BELTS","title":"Ceintures"},{"code":"MEN_BRACES","title":"Bretelles"},{"code":"MEN_ACC_GLOVES","title":"Gants"},{"code":"MEN_HANDKERCHIEFS","title":"Mouchoirs de poche"},{"code":"HATS_CAPS","title":"Chapeaux et casquettes"},{"code":"MEN_POCKET_SQUARES","title":"Pochettes de costume"},{"code":"SCARVES_SHAWLS","title":"Écharpes et châles"},{"code":"MEN_ACC_SUNGLASSES","title":"Lunettes de soleil"},{"code":"MEN_TIES_BOWTIES","title":"Cravates et nœuds papillons"},{"code":"MEN_ACC_WATCHES","title":"Montres"},{"code":"MEN_JEWELRY","title":"Bijoux"},{"code":"MEN_ACC_OTHER","title":"Autres"}]'::jsonb),
  ('MEN_BOOTS', '[{"code":"MEN_CHELSEA_SLIP_ON_BOOTS","title":"Bottines Chelsea et sans lacets"},{"code":"MEN_DESERT_LACE_UP_BOOTS","title":"Bottines à lacets"},{"code":"MEN_SNOW_BOOTS","title":"Bottes de neige"},{"code":"MEN_WELLINGTON","title":"Bottes de pluie"},{"code":"MEN_WORK_BOOTS","title":"Bottes de travail"}]'::jsonb),
  ('MEN_CLOTHING', '[{"code":"MEN_TRO_JEANS","title":"Jeans"},{"code":"MEN_OUTERWEAR_NEW","title":"Manteaux et vestes"},{"code":"MEN_TOPS_T_SHIRTS","title":"Hauts et t-shirts"},{"code":"SUITS_BLAZERS","title":"Costumes et blazers"},{"code":"MEN_PULLOVERS_SWEATERS","title":"Sweats et pulls"},{"code":"MEN_TROUSERS","title":"Pantalons"},{"code":"SHORTS_CAPRI_PANTS","title":"Shorts"},{"code":"UNDERWEAR","title":"Sous-vêtements et chaussettes"},{"code":"MEN_SLEEPWEAR","title":"Pyjamas"},{"code":"MEN_SWIMWEAR","title":"Maillots de bain"},{"code":"SPORTSWEAR","title":"Vêtements de sport et accessoires"},{"code":"SPECIALISED_CLOTHING_COSTUMES","title":"Vêtements spécialisés et costumes"},{"code":"MEN_OTHER","title":"Autres"}]'::jsonb),
  ('MEN_JEWELRY', '[{"code":"MEN_ANKLETS","title":"Bracelets de cheville"},{"code":"MEN_BODY_JEWELLERY","title":"Bijoux de corps"},{"code":"MEN_BRACELETS","title":"Bracelets"},{"code":"MEN_BROOCHES","title":"Broches"},{"code":"MEN_CHARMS_PENDANTS","title":"Breloques et pendentifs"},{"code":"MEN_EARRINGS","title":"Boucles d''oreilles"},{"code":"MEN_JEW_SETS","title":"Ensembles de bijoux"},{"code":"MEN_NECKLACES","title":"Colliers"},{"code":"MEN_JEW_RINGS","title":"Bagues"},{"code":"MEN_JEW_OTHER","title":"Autres bijoux"}]'::jsonb),
  ('MEN_OUTERWEAR_NEW', '[{"code":"MEN_COATS","title":"Manteaux"},{"code":"MEN_OUTERWEAR_VESTS","title":"Vestes sans manches"},{"code":"MEN_JACKETS","title":"Vestes"},{"code":"MEN_PONCHOS","title":"Ponchos"}]'::jsonb),
  ('MEN_PULLOVERS_SWEATERS', '[{"code":"MEN_SWEATERS","title":"Sweats"},{"code":"MEN_PUL_HOODIES_PULLOVERS","title":"Pulls et pulls à capuche"},{"code":"MEN_ZIPHOODIES","title":"Pulls à capuche avec zip"},{"code":"MEN_PUL_CARDIGANS","title":"Cardigans"},{"code":"MEN_CREWNECK_JUMPER","title":"Pulls ras de cou"},{"code":"MEN_PUL_V_NECK_SWEATERS","title":"Sweats à col V"},{"code":"MEN_PUL_TURTLENECK_SWEATERS","title":"Pulls à col roulé"},{"code":"MEN_LONG_SWEATER","title":"Sweats longs"},{"code":"MEN_KNITTED_SWEATER","title":"Pulls d''hiver"},{"code":"OUTDOOR_VEST","title":"Vestes"},{"code":"MEN_PUL_OTHER","title":"Autres"}]'::jsonb),
  ('MEN_SHOES_NEW', '[{"code":"MEN_BOAT_LOAFERS_MOCCASINS","title":"Mocassins et chaussures bateau"},{"code":"MEN_BOOTS","title":"Bottes"},{"code":"MEN_ESPADRILLES","title":"Espadrilles"},{"code":"MEN_FLIPFLOPS_SLIDES","title":"Claquettes et tongs"},{"code":"MEN_FORMAL","title":"Chaussures habillées"},{"code":"MEN_SANDALS_NEW","title":"Sandales"},{"code":"MEN_SLIPPERS_2","title":"Chaussons et pantoufles"},{"code":"SPORT_SHOES_MEN","title":"Chaussures de sport"},{"code":"MEN_SNEAKERS","title":"Baskets"}]'::jsonb),
  ('MEN_SLEEPWEAR', '[{"code":"MEN_ONE_PIECE_PYJAMAS","title":"Pyjamas une-pièce"},{"code":"MEN_PYJAMA_BOTTOMS","title":"Bas de pyjama"},{"code":"MEN_PYJAMA_SETS","title":"Ensembles de pyjamas"},{"code":"MEN_PYJAMA_TOPS","title":"Hauts de pyjama"}]'::jsonb),
  ('MEN_TOPS_T_SHIRTS', '[{"code":"MEN_TOP_SHIRTS","title":"Chemises"},{"code":"MEN_TOP_POLOS","title":"Polos"},{"code":"MEN_TOP_T_SHIRTS","title":"T-shirts"},{"code":"MEN_TOP_VESTS","title":"T-shirts sans manches"}]'::jsonb),
  ('MEN_TROUSERS', '[{"code":"MEN_CHINOS","title":"Chinos"},{"code":"MEN_JOGGERS","title":"Jogging"},{"code":"MEN_TRO_SKINNY_TROUSERS","title":"Pantalons skinny"},{"code":"MEN_SHO_CAPRI_TROUSERS","title":"Pantacourts"},{"code":"MEN_TRO_TAILORED_TROUSERS","title":"Pantalons de costume"},{"code":"MEN_TRO_WIDE_LEGGED_TROUSERS","title":"Pantalons à jambes larges"},{"code":"MEN_TRO_OTHER","title":"Autres pantalons"}]'::jsonb),
  ('MEN_TRO_JEANS', '[{"code":"MEN_RIPPED_JEANS","title":"Jeans troués"},{"code":"MEN_SKINNY_JEANS","title":"Jeans skinny"},{"code":"MEN_SLIMFIT_JEANS","title":"Jeans slim"},{"code":"MEN_STRAIGHTFIT_JEANS","title":"Jeans coupe droite"}]'::jsonb)
)
insert into public.platform_category_aspects
  (platform, category_key, field_key, field_label, required, input_type, allowed_values, source)
select 'opla', category_key, 'category', 'Catégorie', true, 'select', allowed_values, 'manual'
  from niveaux
on conflict (platform, category_key, field_key) do update
  set allowed_values = excluded.allowed_values,
      field_label    = excluded.field_label,
      input_type     = excluded.input_type,
      required       = excluded.required,
      source         = excluded.source,
      last_seen_at   = now();


-- niveaux de choix 91 à 129 sur 129
with niveaux (category_key, allowed_values) as (values
  ('MUSIQUE', '[{"code":"VINYLES","title":"Vinyles"},{"code":"CD","title":"CD"},{"code":"CASSETTES_AUDIO","title":"Cassettes audio"}]'::jsonb),
  ('NURSING_FEEDING', '[{"code":"BABY_BIBS","title":"Bavoirs"},{"code":"BOTTLE_FEEDING","title":"Alimentation au biberon"},{"code":"BREASTFEEDING","title":"Allaitement"},{"code":"BABY_CUP_DISHES_UTENSILS","title":"Repas de bébé"},{"code":"BABY_FEEDING_PILLOW","title":"Coussins et couvertures d''allaitement"},{"code":"DUMMIES_PACIFIERS","title":"Sucettes"}]'::jsonb),
  ('ORDINATEURS_ACCESSOIRES', '[{"code":"HOUSSES_ORDINATEUR_PORTABLE","title":"Housses pour ordinateur portable"},{"code":"HIGHTECH_COQUES_TELEPHONE","title":"Coques et étuis de téléphone"},{"code":"HIGHTECH_PROTECTIONS_ECRAN","title":"Protections d’écran"},{"code":"HIGHTECH_SUPPORTS_GRIPS","title":"Supports, anneaux et bijoux de téléphone"},{"code":"HIGHTECH_CHARGEURS_CABLES","title":"Chargeurs, câbles et batteries externes"},{"code":"HIGHTECH_AUDIO_CASQUES","title":"Casques et écouteurs"},{"code":"HIGHTECH_MONTRES_ACCESSOIRES","title":"Bracelets et coques de montre connectée"},{"code":"HIGHTECH_HOUSSES_TABLETTE","title":"Housses de tablette et liseuse"},{"code":"HIGHTECH_AUTRES","title":"Autres accessoires high-tech"}]'::jsonb),
  ('OUTDOOR_NEW', '[{"code":"BALLPIT_TOYS","title":"Piscines à balles et accessoires"},{"code":"BEACH_WATER_TOYS","title":"Jeux d''eau et de plage"},{"code":"BUBBLE_TOYS","title":"Machines et flacons à bulles"},{"code":"FOAMBLASTER_TOYS","title":"Pistolets à projectiles en mousse et accessoires"},{"code":"GARDEN_GAMES","title":"Autres jeux de plein air"},{"code":"KITE_ROCKET_TOY","title":"Cerfs-volants et fusées"},{"code":"SANDPIT_WATERTABLE_TOY","title":"Jeux de sable et d''eau"},{"code":"SPORTS_TOYS","title":"Jeux de sport"}]'::jsonb),
  ('PULLOVERS_SWEATERS', '[{"code":"HOODIES_JUMPERS","title":"Sweats & sweats à capuche"},{"code":"PULLS_SWEATERS_VESTS","title":"Pulls"},{"code":"WOMEN_WAISTCOAT_SWEATER","title":"Gilets"},{"code":"W_NEW_SWEATERS","title":"Sweats"},{"code":"CARDIGANS","title":"Cardigans"},{"code":"WOM_PUL_OTHER","title":"Autres pull-overs & sweat-shirts"}]'::jsonb),
  ('SHORTS_CAPRIS', '[{"code":"LOW_WAIST_SHORTS","title":"Shorts taille basse"},{"code":"HIGH_WASTED_SHORTS","title":"Shorts taille haute"},{"code":"MEDIUM_LENGTH_SHORTS","title":"Shorts longueur genou"},{"code":"JEANS_SHORTS","title":"Short en jean"},{"code":"LEATHER_SHORTS","title":"Shorts en cuir"},{"code":"CARGO_SHORTS","title":"Shorts cargo"},{"code":"CAPRI_TROUSERS","title":"Pantacourts"},{"code":"WOM_SHO_OTHER","title":"Autres shorts"}]'::jsonb),
  ('SHORTS_CAPRI_PANTS', '[{"code":"MEN_CARGO_SHORTS","title":"Shorts cargo"},{"code":"MEN_CHINO_SHORTS","title":"Shorts chino"},{"code":"MEN_DENIM_SHORTS","title":"Shorts en jean"},{"code":"MEN_SHO_OTHER","title":"Autres shorts"}]'::jsonb),
  ('SKIRTS', '[{"code":"MINI_SKIRTS","title":"Minijupes"},{"code":"WOMEN_KNEE_LENGTH_SKIRTS_REAL","title":"Jupes longueur genou"},{"code":"KNEE_LENGTH_SKIRTS","title":"Jupes midi"},{"code":"MAXI_SKIRTS","title":"Jupes longues"},{"code":"WOMEN_ASYMMETRIC_SKIRTS","title":"Jupes asymétriques"},{"code":"WOMEN_SKORTS","title":"Jupes-shorts"}]'::jsonb),
  ('SLEEPWEAR_BOYS_NEW', '[{"code":"ONEPIECE_PAJAMAS_BOYS","title":"Pyjamas une pièce"},{"code":"TWOPIECE_PAJAMAS_BOYS","title":"Pyjamas deux pièces"}]'::jsonb),
  ('SLEEPWEAR_GIRLS_NEW', '[{"code":"ONEPIECE_PAJAMAS_GIRLS","title":"Pyjamas une pièce"},{"code":"TWOPIECE_PAJAMAS_GIRLS_NEW","title":"Pyjamas deux pièces"},{"code":"NIGHTGOWNS_GIRLS_NEW","title":"Chemises de nuit"}]'::jsonb),
  ('SPORT', '[{"code":"SPORT_CYCLING","title":"Cyclisme"},{"code":"SPORT_HORSE","title":"Équitation"},{"code":"SPORT_OUTDOOR","title":"Sports de plein air"},{"code":"SPORT_FITNESS","title":"Fitness, course à pied et yoga"},{"code":"SPORT_WATER","title":"Sports nautiques"},{"code":"SPORT_TEAM","title":"Sports d''équipe"},{"code":"SPORT_WINTER","title":"Sports d''hiver"},{"code":"SPORT_SKATE","title":"Skateboards et trottinettes"},{"code":"SPORT_RACKET","title":"Sports de raquette"},{"code":"SPORT_MARTIAL","title":"Boxe et arts martiaux"},{"code":"SPORT_GOLF","title":"Golf"},{"code":"SPORT_LEISURE","title":"Sports et jeux de loisir"}]'::jsonb),
  ('SPORTSWEAR', '[{"code":"MEN_SPO_OUTERWEAR","title":"Vêtements d''extérieur"},{"code":"MEN_SPO_TRAINING_COSTUMES","title":"Survêtements"},{"code":"MEN_SPO_TROUSERS","title":"Pantalons"},{"code":"MEN_SPO_SHORTS","title":"Shorts"},{"code":"MEN_SPO_TOPS_T_SHIRTS","title":"Hauts et t-shirts"},{"code":"MEN_JERSEYS","title":"Maillots"},{"code":"MEN_SPO_PULLOVERS_SWEATERS","title":"Pulls & sweats"},{"code":"MEN_SPO_ACCESSORIES","title":"Accessoires de sports"},{"code":"MEN_SPO_OTHER","title":"Autres"}]'::jsonb),
  ('SPORTSWEAR_WOMEN', '[{"code":"WOM_SPO_OUTERWEAR","title":"Vêtements d''extérieur"},{"code":"TRAINING_COSTUMES","title":"Survêtements"},{"code":"WOM_SPO_TROUSERS","title":"Pantalons & leggings"},{"code":"WOM_SPO_SHORTS","title":"Shorts"},{"code":"WOM_SPO_DRESSES","title":"Robes"},{"code":"WOM_SPO_SKIRTS","title":"Jupes"},{"code":"WOM_SPO_TOPS_T_SHIRTS","title":"Hauts & t-shirts"},{"code":"WOM_JERSEYS","title":"Maillots"},{"code":"WOM_SPO_PULLOVERS_SWEATERS","title":"Sweats et sweats à capuche"},{"code":"WOM_SPO_ACCESSORIES","title":"Accessoires de sports"},{"code":"SPORTS_BRA","title":"Brassières"},{"code":"WOM_SPO_OTHER","title":"Autres"}]'::jsonb),
  ('SPORT_CYCLING', '[{"code":"SPORT_BIKE_HELMETS","title":"Casques de vélo"},{"code":"SPORT_BIKE_KIDS","title":"Vélos pour enfant"},{"code":"SPORT_BIKE_ACCESSORIES","title":"Accessoires et outils pour vélo"},{"code":"SPORT_BIKE_PARTS","title":"Pièces pour vélo"},{"code":"SPORT_BIKE_KID_SEATS","title":"Sièges enfants pour vélo"},{"code":"SPORT_BIKE_TRAILERS","title":"Remorques pour vélo"}]'::jsonb),
  ('SPORT_FITNESS', '[{"code":"SPORT_FITNESS_HOME","title":"Accessoires de fitness à domicile"},{"code":"SPORT_FITNESS_BOTTLES","title":"Gourdes"},{"code":"SPORT_FITNESS_RUNNING","title":"Course à pied"},{"code":"SPORT_FITNESS_STRENGTH","title":"Musculation"},{"code":"SPORT_FITNESS_YOGA","title":"Matériel de yoga et de pilates"}]'::jsonb),
  ('SPORT_GOLF', '[{"code":"SPORT_GOLF_BALLS","title":"Balles de golf"},{"code":"SPORT_GOLF_ACCESSORIES","title":"Accessoires de golf"},{"code":"SPORT_GOLF_CLUBS","title":"Clubs de golf"},{"code":"SPORT_GOLF_BAGS","title":"Sacs de golf"},{"code":"SPORT_GOLF_TRAINING","title":"Matériel d''entraînement pour le golf"},{"code":"SPORT_GOLF_GLOVES","title":"Gants de golf"}]'::jsonb),
  ('SPORT_HORSE', '[{"code":"SPORT_HORSE_SADDLES","title":"Selles et harnachement"},{"code":"SPORT_HORSE_PROTECTION","title":"Protections d''équitation"},{"code":"SPORT_HORSE_HELMETS","title":"Bombes d''équitation"},{"code":"SPORT_HORSE_GLOVES","title":"Gants d''équitation"},{"code":"SPORT_HORSE_HELMET_COVERS","title":"Couvre-casques d''équitation"}]'::jsonb),
  ('SPORT_LEISURE', '[{"code":"SPORT_LEISURE_DARTS","title":"Matériel pour fléchettes"},{"code":"SPORT_LEISURE_BOULES","title":"Pétanque et autres jeux"},{"code":"SPORT_LEISURE_BALLS","title":"Balles et ballons"},{"code":"SPORT_LEISURE_BILLIARDS","title":"Billard et snooker"},{"code":"SPORT_LEISURE_FRISBEE","title":"Frisbee et disc golf"},{"code":"SPORT_LEISURE_BOWLING","title":"Bowling"},{"code":"SPORT_LEISURE_SPIKEBALL","title":"Roundnet et spikeball"}]'::jsonb),
  ('SPORT_MARTIAL', '[{"code":"SPORT_MARTIAL_GLOVES","title":"Gants de boxe et d''arts martiaux"},{"code":"SPORT_MARTIAL_OTHER","title":"Autres équipements pour arts martiaux"},{"code":"SPORT_MARTIAL_BODY_PROTECTION","title":"Protections pour le corps"},{"code":"SPORT_MARTIAL_BELTS","title":"Ceintures d''arts martiaux"},{"code":"SPORT_MARTIAL_HEAD_PROTECTION","title":"Protections pour la tête"},{"code":"SPORT_MARTIAL_HAND_WRAPS","title":"Bandes de boxe"},{"code":"SPORT_MARTIAL_PUNCHING_BAGS","title":"Sacs de frappe"},{"code":"SPORT_MARTIAL_PADS","title":"Pattes d''ours, pao et boucliers"},{"code":"SPORT_MARTIAL_SPEED_BAGS","title":"Poires de vitesse"}]'::jsonb),
  ('SPORT_OUTDOOR', '[{"code":"SPORT_OUTDOOR_FISHING_HUNTING","title":"Pêche et chasse"},{"code":"SPORT_OUTDOOR_OTHER_ACCESSORIES","title":"Autres accessoires de sports de plein air"},{"code":"SPORT_OUTDOOR_HIKING_BAGS","title":"Sacs de randonnée"},{"code":"SPORT_OUTDOOR_TENTS","title":"Tentes et matériel de couchage"},{"code":"SPORT_OUTDOOR_BINOCULARS","title":"Jumelles et longues-vues"},{"code":"SPORT_OUTDOOR_LANTERNS","title":"Torches, lampes frontales et lanternes"},{"code":"SPORT_OUTDOOR_CLIMBING","title":"Escalade et escalade de bloc"},{"code":"SPORT_OUTDOOR_CAMP_COOKING","title":"Réchauds et ustensiles de cuisine de camping"},{"code":"SPORT_OUTDOOR_CAMP_FURNITURE","title":"Meubles de camping"},{"code":"SPORT_OUTDOOR_COOLERS","title":"Glacières"},{"code":"SPORT_OUTDOOR_HYDRATION","title":"Systèmes et kits d''hydratation"},{"code":"SPORT_OUTDOOR_COMPASSES","title":"Boussoles"},{"code":"SPORT_OUTDOOR_TREKKING_POLES","title":"Bâtons de randonnée"}]'::jsonb),
  ('SPORT_RACKET', '[{"code":"SPORT_RACKET_TENNIS","title":"Tennis"},{"code":"SPORT_RACKET_PADEL","title":"Padel"},{"code":"SPORT_RACKET_TABLE_TENNIS","title":"Tennis de table"},{"code":"SPORT_RACKET_BADMINTON","title":"Badminton"},{"code":"SPORT_RACKET_SQUASH","title":"Squash"},{"code":"SPORT_RACKET_EYE_PROTECTION","title":"Protections pour les yeux"},{"code":"SPORT_RACKET_PICKLEBALL","title":"Pickleball"},{"code":"SPORT_RACKET_RACQUETBALL","title":"Racquetball"}]'::jsonb),
  ('SPORT_SHOES_MEN', '[{"code":"MEN_BASKETBALL_SHOES","title":"Chaussures de basket"},{"code":"MEN_CLIMBING_BOULDERING_SHOES","title":"Chaussures d''escalade"},{"code":"MEN_CYCLING_SHOES","title":"Chaussures de cyclisme"},{"code":"MEN_DANCE_SHOES","title":"Chaussures de danse"},{"code":"MEN_FOOTBALL_BOOTS","title":"Chaussures de foot"},{"code":"MEN_GOLF_SHOES","title":"Chaussures de golf"},{"code":"MEN_HIKING_BOOTS_SHOES","title":"Chaussures et bottes de randonnée"},{"code":"MEN_ICE_SKATES","title":"Patins à glace"},{"code":"MEN_INDOOR_FOOTBALL_SHOES","title":"Chaussures de foot en salle"},{"code":"SPORT_SHOES_INDOOR_MEN","title":"Chaussures de fitness"},{"code":"MEN_MOTORBIKE_BOOTS","title":"Bottes de moto"},{"code":"MEN_ROLLER_SKATES_BLADES","title":"Patins à roulettes et rollers"},{"code":"SPORT_SHOES_RUNNING_MEN","title":"Chaussures de course"},{"code":"MEN_SKI_BOOTS","title":"Bottes de ski"},{"code":"MEN_SNOWBOARD_BOOTS","title":"Bottes de snowboard"},{"code":"MEN_SWIMMING_WATER_SHOES","title":"Chaussures aquatiques"},{"code":"MEN_TENNIS_SHOES","title":"Chaussures de tennis"}]'::jsonb),
  ('SPORT_SKATE', '[{"code":"SPORT_SKATE_PROTECTION","title":"Protections de skate"},{"code":"SPORT_SKATE_SKATEBOARD_PARTS","title":"Pièces et accessoires pour skateboard"},{"code":"SPORT_SKATE_SKATING_PARTS","title":"Pièces et accessoires pour skating"},{"code":"SPORT_SKATE_HELMETS","title":"Casques de skate"}]'::jsonb),
  ('SPORT_TEAM', '[{"code":"SPORT_TEAM_FOOTBALL","title":"Football"},{"code":"SPORT_TEAM_HANDBALL","title":"Handball"},{"code":"SPORT_TEAM_VOLLEYBALL","title":"Volley-ball"},{"code":"SPORT_TEAM_RUGBY","title":"Rugby"},{"code":"SPORT_TEAM_AMERICAN_FOOTBALL","title":"Football américain"},{"code":"SPORT_TEAM_BASEBALL","title":"Baseball et softball"},{"code":"SPORT_TEAM_CRICKET","title":"Cricket"},{"code":"SPORT_TEAM_FIELD_HOCKEY","title":"Hockey sur gazon"},{"code":"SPORT_TEAM_FLOORBALL","title":"Floorball"},{"code":"SPORT_TEAM_GAELIC","title":"Sports gaéliques"},{"code":"SPORT_TEAM_LACROSSE","title":"Lacrosse"},{"code":"SPORT_TEAM_NETBALL","title":"Netball"},{"code":"SPORT_TEAM_OTHER","title":"Autres équipements pour sports d''équipe"},{"code":"SPORT_TEAM_TRAINING","title":"Matériel d''entraînement et d''arbitrage"},{"code":"SPORT_TEAM_BASKETBALL","title":"Basketball"}]'::jsonb),
  ('SPORT_WATER', '[{"code":"SPORT_WATER_SWIMMING","title":"Natation"},{"code":"SPORT_WATER_WETSUITS","title":"Combinaisons, gants et chaussons"},{"code":"SPORT_WATER_ACCESSORIES","title":"Accessoires pour sports nautiques"},{"code":"SPORT_WATER_PFD","title":"Gilets de flottaison"},{"code":"SPORT_WATER_INFLATABLES","title":"Bateaux gonflables"},{"code":"SPORT_WATER_HELMETS","title":"Casques pour sports nautiques"},{"code":"SPORT_WATER_TOWABLES","title":"Bouées tractées"},{"code":"SPORT_WATER_SKIMBOARDS","title":"Skimboards"}]'::jsonb),
  ('SPORT_WINTER', '[{"code":"SPORT_WINTER_SKI_GEAR","title":"Matériel de ski"},{"code":"SPORT_WINTER_HELMETS","title":"Casques pour sports d''hiver"},{"code":"SPORT_WINTER_GOGGLES","title":"Masques et lunettes de ski"},{"code":"SPORT_WINTER_SNOWBOARD_GEAR","title":"Matériel de snowboard"},{"code":"SPORT_WINTER_ICE_HOCKEY","title":"Hockey sur glace"},{"code":"SPORT_WINTER_FIGURE_SKATING","title":"Accessoires de patinage artistique"},{"code":"SPORT_WINTER_SNOWSHOES","title":"Raquettes à neige"},{"code":"SPORT_WINTER_GAITERS","title":"Guêtres"}]'::jsonb),
  ('SUITS_BLAZERS', '[{"code":"BLAZERS_MEN","title":"Blazers"},{"code":"SUIT_PANTS","title":"Pantalons de costume"},{"code":"SUIT_WAISTCOAT","title":"Gilets de costume"},{"code":"SUIT_SET_MEN","title":"Ensembles costume"},{"code":"WEDDING_SUIT","title":"Costumes de mariage"},{"code":"SUITS_BLAZERS_OTHER","title":"Autres"}]'::jsonb),
  ('SWIMWEAR', '[{"code":"ONE_PIECES","title":"Une pièce"},{"code":"TWO_PIECE_SWIMWEAR","title":"Deux pièces"},{"code":"COVERUP_SWIMWEAR","title":"Paréos et sarongs"},{"code":"WOM_SWI_OTHER","title":"Autres"}]'::jsonb),
  ('TOPS_T_SHIRTS', '[{"code":"SHIRTS","title":"Chemises"},{"code":"BLOUSES","title":"Blouses"},{"code":"VESTS","title":"Vestes"},{"code":"WOM_TOP_T_SHIRTS","title":"T-shirts"},{"code":"WOM_TOP_T_SHIRTS_LONG_SLEEVE","title":"T-shirts manches longues"},{"code":"TANK_TOPS","title":"Débardeurs"},{"code":"TUNICS","title":"Tuniques ou blouses"},{"code":"CROP_TOPS","title":"Tops courts"},{"code":"SHORT_SLEEVE_BLOUSES","title":"Blouses manches courtes"},{"code":"MIDDLE_SLEEVE_BLOUSES","title":"Blouses ¾"},{"code":"LONG_SLEEVE_BLOUSES","title":"Blouses manches longues"},{"code":"TOPS_BODIES","title":"Bodies"},{"code":"TUBE_TOPS","title":"Tops épaules dénudées"},{"code":"W_TURTLENECKS","title":"Cols roulés"},{"code":"PEPLUM_TOPS","title":"Tops peplum"},{"code":"HALTER_TOPS","title":"Tops dos nu"},{"code":"WOM_TOP_OTHER","title":"Autres hauts"}]'::jsonb),
  ('TOYS_AND_GAMES', '[{"code":"ACTION_FIGURES_NEW","title":"Figurines et accessoires"},{"code":"BOARD_GAMES","title":"Jeux de société"},{"code":"KID_CRAFTS","title":"Loisirs créatifs"},{"code":"BABY_ACTIVITIES_TOYS","title":"Activités et jouets pour bébé"},{"code":"CONSTRUCTION_NEW","title":"Jeux de construction"},{"code":"DOLLS_NEW","title":"Poupées, poupons et accessoires"},{"code":"TOY_PRETEND_PLAY","title":"Déguisements"},{"code":"EDUCATIONAL_TOYS_NEW","title":"Jeux éducatifs"},{"code":"ELECTRONIC_NEW","title":"Jeux et jouets électroniques"},{"code":"MUSICAL_NEW","title":"Jeux/jouets musicaux et instruments"},{"code":"NOVELTY_FIDGET_TOYS","title":"Jeux de cirque, fidgets et gadgets"},{"code":"OUTDOOR_NEW","title":"Jeux de sport et de plein air"},{"code":"STUFFED_ANIMALS_NEW","title":"Peluches"},{"code":"VEHICLE_TOYS","title":"Voitures, trains et autres véhicules"},{"code":"PUZZLES","title":"Puzzles"},{"code":"TABLETOP_GAMES","title":"Jeux de plateau"}]'::jsonb),
  ('TROUSERS', '[{"code":"W_REGULAR_PANTS","title":"Pantalons"},{"code":"CROPPED_PANTS","title":"Pantalons courts & chinos"},{"code":"WIDE_LEG_PANTS","title":"Pantalons à jambes larges"},{"code":"SKINNY_TROUSERS","title":"Pantalons skinny"},{"code":"TAILORED_TROUSERS","title":"Pantalons ajustés"},{"code":"W_SLIM_STRAIGHT_PANTS","title":"Pantalons droits"},{"code":"LEATHER_TROUSERS","title":"Pantalons en cuir"},{"code":"LEGGINGS","title":"Leggings"},{"code":"JOGGINGS","title":"Joggings"},{"code":"HAREMS","title":"Sarouels"},{"code":"WOM_TRO_OTHER","title":"Autres pantalons"}]'::jsonb),
  ('UNDERWEAR', '[{"code":"MEN_UNDERWEAR","title":"Sous-vêtements"},{"code":"MEN_SOCKS","title":"Chaussettes"},{"code":"MEN_ROBES","title":"Peignoirs"},{"code":"OTHER_MEN_UNDERWEAR","title":"Autres"}]'::jsonb),
  ('VEHICLE_TOYS', '[{"code":"TOY_PLANES","title":"Avions"},{"code":"TOY_CARS","title":"Voitures"},{"code":"TOY_TRAINS","title":"Trains"},{"code":"TRUCKS","title":"Camions"},{"code":"TOY_TRACK_GARAGE","title":"Circuits et garages"},{"code":"OTHER_TOY_VEHICLES","title":"Autres véhicules"}]'::jsonb),
  ('VIDEO', '[{"code":"DVD","title":"DVD"},{"code":"BLURAY","title":"Blu-ray"}]'::jsonb),
  ('WOMENS', '[{"code":"COATS_JACKETS","title":"Manteaux et vestes"},{"code":"PULLOVERS_SWEATERS","title":"Pulls, sweats et gilets"},{"code":"BLAZERS","title":"Blazers et tailleurs"},{"code":"DRESSES","title":"Robes"},{"code":"SKIRTS","title":"Jupes"},{"code":"TOPS_T_SHIRTS","title":"Chemises, hauts et t-shirts"},{"code":"JEANS","title":"Jeans"},{"code":"TROUSERS","title":"Pantalons et leggings"},{"code":"SHORTS_CAPRIS","title":"Shorts"},{"code":"JUMPSUITS_UK","title":"Combinaisons et combishorts"},{"code":"SWIMWEAR","title":"Maillots de bain"},{"code":"LINGERIE","title":"Lingerie et pyjamas"},{"code":"MATERNITY_CLOTHES_MAIN","title":"Maternité"},{"code":"SPORTSWEAR_WOMEN","title":"Vêtements de sport"},{"code":"SPECIAL_OUTFITS_COSTUMES_W","title":"Costumes et tenues particulières"},{"code":"OTHER_CLOTHES","title":"Autres"}]'::jsonb),
  ('WOMEN_ROOT', '[{"code":"WOMENS","title":"Vêtements"},{"code":"FOOTWEAR","title":"Chaussures"},{"code":"BAGS_BACKPACKS","title":"Sacs"},{"code":"ACCESSORIES_JEWELLERY","title":"Accessoires"},{"code":"BEAUTY","title":"Beauté"}]'::jsonb),
  ('WOMEN_SPORT_SHOES', '[{"code":"WOMEN_BASKETBALL_SHOES","title":"Chaussures de basket"},{"code":"WOMEN_CLIMBING_BOULDERING_SHOES","title":"Chaussures d''escalade"},{"code":"WOMEN_CYCLING_SHOES","title":"Chaussures de cyclisme"},{"code":"WOMEN_DANCE_SHOES","title":"Chaussures de danse"},{"code":"WOMEN_FOOTBALL_BOOTS","title":"Chaussures de foot"},{"code":"WOMEN_GOLF_SHOES","title":"Chaussures de golf"},{"code":"WOMEN_HIKING_BOOTS_SHOES","title":"Chaussures et bottes de randonnée"},{"code":"WOMEN_ICE_SKATES","title":"Patins à glace"},{"code":"WOMEN_INDOOR_FOOTBALL_SHOES","title":"Chaussures de foot en salle"},{"code":"WOMEN_INDOOR_TRAINING_SHOES","title":"Chaussures de fitness"},{"code":"WOMEN_MOTORBIKE_BOOTS","title":"Bottes de moto"},{"code":"WOMEN_ROLLER_SKATES_BLADES","title":"Patins à roulettes et rollers"},{"code":"WOMEN_RUNNING_SHOES","title":"Chaussures de course"},{"code":"WOMEN_SKI_BOOTS","title":"Chaussures de ski"},{"code":"WOMEN_SNOWBOARD_BOOTS","title":"Bottes de snowboard"},{"code":"WOMEN_SWIMMING_WATER_SHOES","title":"Chaussures aquatiques"},{"code":"WOMEN_TENNIS_SHOES","title":"Chaussures de tennis"}]'::jsonb),
  ('WOM_ACC_HATS_CAPS', '[{"code":"WOMEN_BALACLAVAS","title":"Cagoules"},{"code":"WOMEN_BEANIES","title":"Bonnets"},{"code":"CAPS","title":"Casquettes"},{"code":"WOMEN_EARMUFFS","title":"Cache-oreilles"},{"code":"HATS","title":"Chapeaux"},{"code":"HEADBANDS","title":"Bandeaux"}]'::jsonb),
  ('W_BOOTS', '[{"code":"WOMEN_ANKLE_BOOTS","title":"Bottines"},{"code":"WOMEN_MID_CALF_BOOTS","title":"Bottes mi-hautes"},{"code":"KNEE_LENGHT_BOOTS","title":"Bottes hautes"},{"code":"WOMEN_OVER_KNEE_BOOTS","title":"Cuissardes"},{"code":"WOMEN_SNOW_BOOTS","title":"Bottes de neige"},{"code":"WELLINGTON_BOOTS","title":"Bottes de pluie"},{"code":"WOMEN_WORK_BOOTS","title":"Bottes de travail"}]'::jsonb)
)
insert into public.platform_category_aspects
  (platform, category_key, field_key, field_label, required, input_type, allowed_values, source)
select 'opla', category_key, 'category', 'Catégorie', true, 'select', allowed_values, 'manual'
  from niveaux
on conflict (platform, category_key, field_key) do update
  set allowed_values = excluded.allowed_values,
      field_label    = excluded.field_label,
      input_type     = excluded.input_type,
      required       = excluded.required,
      source         = excluded.source,
      last_seen_at   = now();


-- les 397 feuilles qui ont une grille — la grille est écrite UNE fois, et jointe
with grilles (nom, allowed_values) as (values
  ('G1', '[{"code":"TAILLE_UNIQUE","title":"Taille unique"},{"code":"XXS","title":"XXS"},{"code":"XS","title":"XS"},{"code":"S","title":"S"},{"code":"M","title":"M"},{"code":"L","title":"L"},{"code":"XL","title":"XL"},{"code":"XXL","title":"XXL"},{"code":"3XL","title":"3XL"},{"code":"4XL","title":"4XL"},{"code":"5XL","title":"5XL"},{"code":"6XL","title":"6XL"},{"code":"7XL","title":"7XL"},{"code":"8XL","title":"8XL"}]'::jsonb),
  ('G2', '[{"code":"0M","title":"0 mois"},{"code":"0-3M","title":"0-3 mois"},{"code":"1M","title":"1 mois"},{"code":"3M","title":"3 mois"},{"code":"3-6M","title":"3-6 mois"},{"code":"6M","title":"6 mois"},{"code":"9M","title":"9 mois"},{"code":"6-12M","title":"6-12 mois"},{"code":"12M","title":"12 mois"},{"code":"12-18M","title":"12-18 mois"},{"code":"18M","title":"18 mois"},{"code":"18-24M","title":"18-24 mois"},{"code":"24M","title":"24 mois"},{"code":"36M","title":"36 mois"},{"code":"2Y","title":"2 ans"},{"code":"3Y","title":"3 ans"},{"code":"4Y","title":"4 ans"},{"code":"5Y","title":"5 ans"},{"code":"6Y","title":"6 ans"},{"code":"7Y","title":"7 ans"},{"code":"8Y","title":"8 ans"},{"code":"9Y","title":"9 ans"},{"code":"10Y","title":"10 ans"},{"code":"11Y","title":"11 ans"},{"code":"12Y","title":"12 ans"},{"code":"13Y","title":"13 ans"},{"code":"14Y","title":"14 ans"},{"code":"15Y","title":"15 ans"},{"code":"16Y","title":"16 ans"}]'::jsonb),
  ('G3', '[{"code":"14","title":"14"},{"code":"15","title":"15"},{"code":"16","title":"16"},{"code":"17","title":"17"},{"code":"18","title":"18"},{"code":"19","title":"19"},{"code":"20","title":"20"},{"code":"21","title":"21"},{"code":"22","title":"22"},{"code":"23","title":"23"},{"code":"24","title":"24"},{"code":"25","title":"25"},{"code":"26","title":"26"},{"code":"27","title":"27"},{"code":"28","title":"28"},{"code":"29","title":"29"},{"code":"30","title":"30"},{"code":"31","title":"31"},{"code":"32","title":"32"},{"code":"33","title":"33"},{"code":"34","title":"34"},{"code":"35","title":"35"},{"code":"36","title":"36"},{"code":"37","title":"37"},{"code":"38","title":"38"},{"code":"39","title":"39"},{"code":"40","title":"40"},{"code":"41","title":"41"},{"code":"42","title":"42"},{"code":"43","title":"43"},{"code":"44","title":"44"},{"code":"45","title":"45"},{"code":"46","title":"46"},{"code":"47","title":"47"},{"code":"48","title":"48"},{"code":"49","title":"49"},{"code":"50","title":"50"}]'::jsonb),
  ('G4', '[{"code":"TAILLE_UNIQUE","title":"Taille unique"},{"code":"XS","title":"XS"},{"code":"S","title":"S"},{"code":"M","title":"M"},{"code":"L","title":"L"},{"code":"XL","title":"XL"},{"code":"XXL","title":"XXL"},{"code":"75A","title":"75A"},{"code":"80A","title":"80A"},{"code":"85A","title":"85A"},{"code":"90A","title":"90A"},{"code":"95A","title":"95A"},{"code":"100A","title":"100A"},{"code":"105A","title":"105A"},{"code":"110A","title":"110A"},{"code":"115A","title":"115A"},{"code":"75B","title":"75B"},{"code":"80B","title":"80B"},{"code":"85B","title":"85B"},{"code":"90B","title":"90B"},{"code":"95B","title":"95B"},{"code":"100B","title":"100B"},{"code":"105B","title":"105B"},{"code":"110B","title":"110B"},{"code":"115B","title":"115B"},{"code":"75C","title":"75C"},{"code":"80C","title":"80C"},{"code":"85C","title":"85C"},{"code":"90C","title":"90C"},{"code":"95C","title":"95C"},{"code":"100C","title":"100C"},{"code":"105C","title":"105C"},{"code":"110C","title":"110C"},{"code":"115C","title":"115C"},{"code":"75D","title":"75D"},{"code":"80D","title":"80D"},{"code":"85D","title":"85D"},{"code":"90D","title":"90D"},{"code":"95D","title":"95D"},{"code":"100D","title":"100D"},{"code":"105D","title":"105D"},{"code":"110D","title":"110D"},{"code":"115D","title":"115D"},{"code":"75E","title":"75E"},{"code":"80E","title":"80E"},{"code":"85E","title":"85E"},{"code":"90E","title":"90E"},{"code":"95E","title":"95E"},{"code":"100E","title":"100E"},{"code":"105E","title":"105E"},{"code":"110E","title":"110E"},{"code":"115E","title":"115E"},{"code":"75F","title":"75F"},{"code":"80F","title":"80F"},{"code":"85F","title":"85F"},{"code":"90F","title":"90F"},{"code":"95F","title":"95F"},{"code":"100F","title":"100F"},{"code":"105F","title":"105F"},{"code":"110F","title":"110F"},{"code":"115F","title":"115F"},{"code":"75G","title":"75G"},{"code":"80G","title":"80G"},{"code":"85G","title":"85G"},{"code":"90G","title":"90G"},{"code":"95G","title":"95G"},{"code":"100G","title":"100G"},{"code":"105G","title":"105G"},{"code":"110G","title":"110G"},{"code":"115G","title":"115G"}]'::jsonb)
), feuilles (category_key, nom) as (values
  ('CAPES_PONCHOS', 'G1'),
  ('W_COATS', 'G1'),
  ('WOMEN_OUTERWEAR_VESTS', 'G1'),
  ('W_JACKETS', 'G1'),
  ('W_BOMBERS', 'G1'),
  ('W_RAINCOATS', 'G1'),
  ('HOODIES_JUMPERS', 'G1'),
  ('PULLS_SWEATERS_VESTS', 'G1'),
  ('WOMEN_WAISTCOAT_SWEATER', 'G1'),
  ('W_NEW_SWEATERS', 'G1'),
  ('CARDIGANS', 'G1'),
  ('WOM_PUL_OTHER', 'G1'),
  ('WOM_BLA_BLAZERS', 'G1'),
  ('W_PANTSUITS', 'G1'),
  ('W_SKIRT_SUITS', 'G1'),
  ('W_SUIT_SEPARATES', 'G1'),
  ('W_OTHER_SUITS_BLAZERS', 'G1'),
  ('MAXI_DRESSES', 'G1'),
  ('OCCASIONAL_DRESSES', 'G1'),
  ('SUMMER_DRESSES', 'G1'),
  ('WINTER_DRESSES', 'G1'),
  ('FORMAL_DRESSES', 'G1'),
  ('CASUAL_DRESSES', 'G1'),
  ('STRAPLESS_DRESSES', 'G1'),
  ('LITTLE_BLACK_DRESSES', 'G1'),
  ('JEANS_DRESSES_TUNICS', 'G1'),
  ('WOM_DRE_OTHER', 'G1'),
  ('MINI_SKIRTS', 'G1'),
  ('WOMEN_KNEE_LENGTH_SKIRTS_REAL', 'G1'),
  ('KNEE_LENGTH_SKIRTS', 'G1'),
  ('MAXI_SKIRTS', 'G1'),
  ('WOMEN_ASYMMETRIC_SKIRTS', 'G1'),
  ('WOMEN_SKORTS', 'G1'),
  ('SHIRTS', 'G1'),
  ('BLOUSES', 'G1'),
  ('VESTS', 'G1'),
  ('WOM_TOP_T_SHIRTS', 'G1'),
  ('WOM_TOP_T_SHIRTS_LONG_SLEEVE', 'G1'),
  ('TANK_TOPS', 'G1'),
  ('TUNICS', 'G1'),
  ('CROP_TOPS', 'G1'),
  ('SHORT_SLEEVE_BLOUSES', 'G1'),
  ('MIDDLE_SLEEVE_BLOUSES', 'G1'),
  ('LONG_SLEEVE_BLOUSES', 'G1'),
  ('TOPS_BODIES', 'G1'),
  ('TUBE_TOPS', 'G1'),
  ('W_TURTLENECKS', 'G1'),
  ('PEPLUM_TOPS', 'G1'),
  ('HALTER_TOPS', 'G1'),
  ('WOM_TOP_OTHER', 'G1'),
  ('W_CROPPED_JEANS', 'G1'),
  ('FLARED_JEANS', 'G1'),
  ('W_HIGH_WAIST_JEANS', 'G1'),
  ('W_RIPPED_JEANS', 'G1'),
  ('W_SKINNY_JEANS', 'G1'),
  ('W_STRAIGHT_JEANS', 'G1'),
  ('JEANS_OTHER', 'G1'),
  ('W_REGULAR_PANTS', 'G1'),
  ('CROPPED_PANTS', 'G1'),
  ('WIDE_LEG_PANTS', 'G1'),
  ('SKINNY_TROUSERS', 'G1'),
  ('TAILORED_TROUSERS', 'G1'),
  ('W_SLIM_STRAIGHT_PANTS', 'G1'),
  ('LEATHER_TROUSERS', 'G1'),
  ('LEGGINGS', 'G1'),
  ('JOGGINGS', 'G1'),
  ('HAREMS', 'G1'),
  ('WOM_TRO_OTHER', 'G1'),
  ('LOW_WAIST_SHORTS', 'G1'),
  ('HIGH_WASTED_SHORTS', 'G1'),
  ('MEDIUM_LENGTH_SHORTS', 'G1'),
  ('JEANS_SHORTS', 'G1'),
  ('LEATHER_SHORTS', 'G1'),
  ('CARGO_SHORTS', 'G1'),
  ('CAPRI_TROUSERS', 'G1'),
  ('WOM_SHO_OTHER', 'G1'),
  ('W_JUMPSUITS', 'G1'),
  ('W_ROMPERS', 'G1'),
  ('W_OTHER_ROMPERS_JUMPSUITS', 'G1'),
  ('ONE_PIECES', 'G1'),
  ('TWO_PIECE_SWIMWEAR', 'G1'),
  ('COVERUP_SWIMWEAR', 'G1'),
  ('WOM_SWI_OTHER', 'G1'),
  ('BRAS', 'G4'),
  ('PANTIES_THONGS', 'G1'),
  ('WOM_LIN_SETS', 'G1'),
  ('NIGHTWEAR', 'G1'),
  ('DRESSING_GOWNS', 'G1'),
  ('INTIMATES_TIGHTS', 'G1'),
  ('INTIMATES_SOCKS', 'G1'),
  ('LINGERIE_ACC', 'G1'),
  ('WOM_LIN_OTHER', 'G1'),
  ('MATERNITY_TOPS', 'G1'),
  ('MATERNITY_DRESSES', 'G1'),
  ('MATERNITY_SKIRTS', 'G1'),
  ('MATERNITY_PANTS', 'G1'),
  ('MATERNITY_SHORTS', 'G1'),
  ('MATERNITY_ROMPERS_JUMPSUITS', 'G1'),
  ('MATERNITY_HOODIES_SWEATERS', 'G1'),
  ('MATERNITY_COATS_JACKETS', 'G1'),
  ('MATERNITY_SWIMWEAR_BEACHWEAR', 'G1'),
  ('MATERNITY_UNDERWEAR', 'G1'),
  ('MATERNITY_SPORT', 'G1'),
  ('WOM_SPO_OUTERWEAR', 'G1'),
  ('TRAINING_COSTUMES', 'G1'),
  ('WOM_SPO_TROUSERS', 'G1'),
  ('WOM_SPO_SHORTS', 'G1'),
  ('WOM_SPO_DRESSES', 'G1'),
  ('WOM_SPO_SKIRTS', 'G1'),
  ('WOM_SPO_TOPS_T_SHIRTS', 'G1'),
  ('WOM_JERSEYS', 'G1'),
  ('WOM_SPO_PULLOVERS_SWEATERS', 'G1'),
  ('WOM_SPO_ACCESSORIES', 'G1'),
  ('SPORTS_BRA', 'G1'),
  ('WOM_SPO_OTHER', 'G1'),
  ('SPECIAL_OUTFITS_COSTUMES_W', 'G1'),
  ('OTHER_CLOTHES', 'G1'),
  ('WOMEN_BALLERINAS', 'G3'),
  ('WOMEN_BOAT_SHOES_LOAFERS_MOCCASINS', 'G3'),
  ('WOMEN_ANKLE_BOOTS', 'G3'),
  ('WOMEN_MID_CALF_BOOTS', 'G3'),
  ('KNEE_LENGHT_BOOTS', 'G3'),
  ('WOMEN_OVER_KNEE_BOOTS', 'G3'),
  ('WOMEN_SNOW_BOOTS', 'G3'),
  ('WELLINGTON_BOOTS', 'G3'),
  ('WOMEN_WORK_BOOTS', 'G3'),
  ('WOMEN_CLOGS_MULES', 'G3'),
  ('WOMEN_ESPADRILLES', 'G3'),
  ('WOMEN_FLIPFLOPS_SLIDES', 'G3'),
  ('HIGH_HEELS', 'G3'),
  ('WOMEN_LACE_UP_SHOES', 'G3'),
  ('WOMEN_SANDALS', 'G3'),
  ('SLIPPERS', 'G3'),
  ('WOMEN_BASKETBALL_SHOES', 'G3'),
  ('WOMEN_CLIMBING_BOULDERING_SHOES', 'G3'),
  ('WOMEN_CYCLING_SHOES', 'G3'),
  ('WOMEN_DANCE_SHOES', 'G3'),
  ('WOMEN_FOOTBALL_BOOTS', 'G3'),
  ('WOMEN_GOLF_SHOES', 'G3'),
  ('WOMEN_HIKING_BOOTS_SHOES', 'G3'),
  ('WOMEN_ICE_SKATES', 'G3'),
  ('WOMEN_INDOOR_FOOTBALL_SHOES', 'G3'),
  ('WOMEN_INDOOR_TRAINING_SHOES', 'G3'),
  ('WOMEN_MOTORBIKE_BOOTS', 'G3'),
  ('WOMEN_ROLLER_SKATES_BLADES', 'G3'),
  ('WOMEN_RUNNING_SHOES', 'G3'),
  ('WOMEN_SKI_BOOTS', 'G3'),
  ('WOMEN_SNOWBOARD_BOOTS', 'G3'),
  ('WOMEN_SWIMMING_WATER_SHOES', 'G3'),
  ('WOMEN_TENNIS_SHOES', 'G3'),
  ('WOMEN_TRAINERS', 'G3'),
  ('BELTS', 'G1'),
  ('GLOVES', 'G1'),
  ('W_OTHER_ACCESSORIES', 'G1'),
  ('MEN_RIPPED_JEANS', 'G1'),
  ('MEN_SKINNY_JEANS', 'G1'),
  ('MEN_SLIMFIT_JEANS', 'G1'),
  ('MEN_STRAIGHTFIT_JEANS', 'G1'),
  ('MEN_COATS', 'G1'),
  ('MEN_OUTERWEAR_VESTS', 'G1'),
  ('MEN_JACKETS', 'G1'),
  ('MEN_PONCHOS', 'G1'),
  ('MEN_TOP_SHIRTS', 'G1'),
  ('MEN_TOP_POLOS', 'G1'),
  ('MEN_TOP_T_SHIRTS', 'G1'),
  ('MEN_TOP_VESTS', 'G1'),
  ('BLAZERS_MEN', 'G1'),
  ('SUIT_PANTS', 'G1'),
  ('SUIT_WAISTCOAT', 'G1'),
  ('SUIT_SET_MEN', 'G1'),
  ('WEDDING_SUIT', 'G1'),
  ('SUITS_BLAZERS_OTHER', 'G1'),
  ('MEN_SWEATERS', 'G1'),
  ('MEN_PUL_HOODIES_PULLOVERS', 'G1'),
  ('MEN_ZIPHOODIES', 'G1'),
  ('MEN_PUL_CARDIGANS', 'G1'),
  ('MEN_CREWNECK_JUMPER', 'G1'),
  ('MEN_PUL_V_NECK_SWEATERS', 'G1'),
  ('MEN_PUL_TURTLENECK_SWEATERS', 'G1'),
  ('MEN_LONG_SWEATER', 'G1'),
  ('MEN_KNITTED_SWEATER', 'G1'),
  ('OUTDOOR_VEST', 'G1'),
  ('MEN_PUL_OTHER', 'G1'),
  ('MEN_CHINOS', 'G1'),
  ('MEN_JOGGERS', 'G1'),
  ('MEN_TRO_SKINNY_TROUSERS', 'G1'),
  ('MEN_SHO_CAPRI_TROUSERS', 'G1'),
  ('MEN_TRO_TAILORED_TROUSERS', 'G1'),
  ('MEN_TRO_WIDE_LEGGED_TROUSERS', 'G1'),
  ('MEN_TRO_OTHER', 'G1'),
  ('MEN_CARGO_SHORTS', 'G1'),
  ('MEN_CHINO_SHORTS', 'G1'),
  ('MEN_DENIM_SHORTS', 'G1'),
  ('MEN_SHO_OTHER', 'G1'),
  ('MEN_UNDERWEAR', 'G1'),
  ('MEN_SOCKS', 'G1'),
  ('MEN_ROBES', 'G1'),
  ('OTHER_MEN_UNDERWEAR', 'G1'),
  ('MEN_ONE_PIECE_PYJAMAS', 'G1'),
  ('MEN_PYJAMA_BOTTOMS', 'G1'),
  ('MEN_PYJAMA_SETS', 'G1'),
  ('MEN_PYJAMA_TOPS', 'G1'),
  ('MEN_SWIMWEAR', 'G1'),
  ('MEN_SPO_OUTERWEAR', 'G1'),
  ('MEN_SPO_TRAINING_COSTUMES', 'G1'),
  ('MEN_SPO_TROUSERS', 'G1'),
  ('MEN_SPO_SHORTS', 'G1'),
  ('MEN_SPO_TOPS_T_SHIRTS', 'G1'),
  ('MEN_JERSEYS', 'G1'),
  ('MEN_SPO_PULLOVERS_SWEATERS', 'G1'),
  ('MEN_SPO_ACCESSORIES', 'G1'),
  ('MEN_SPO_OTHER', 'G1'),
  ('SPECIALISED_CLOTHING_COSTUMES', 'G1'),
  ('MEN_OTHER', 'G1'),
  ('MEN_BOAT_LOAFERS_MOCCASINS', 'G3'),
  ('MEN_CHELSEA_SLIP_ON_BOOTS', 'G3'),
  ('MEN_DESERT_LACE_UP_BOOTS', 'G3'),
  ('MEN_SNOW_BOOTS', 'G3'),
  ('MEN_WELLINGTON', 'G3'),
  ('MEN_WORK_BOOTS', 'G3'),
  ('MEN_ESPADRILLES', 'G3'),
  ('MEN_FLIPFLOPS_SLIDES', 'G3'),
  ('MEN_FORMAL', 'G3'),
  ('MEN_SANDALS_NEW', 'G3'),
  ('MEN_SLIPPERS_2', 'G3'),
  ('MEN_BASKETBALL_SHOES', 'G3'),
  ('MEN_CLIMBING_BOULDERING_SHOES', 'G3'),
  ('MEN_CYCLING_SHOES', 'G3'),
  ('MEN_DANCE_SHOES', 'G3'),
  ('MEN_FOOTBALL_BOOTS', 'G3'),
  ('MEN_GOLF_SHOES', 'G3'),
  ('MEN_HIKING_BOOTS_SHOES', 'G3'),
  ('MEN_ICE_SKATES', 'G3'),
  ('MEN_INDOOR_FOOTBALL_SHOES', 'G3'),
  ('SPORT_SHOES_INDOOR_MEN', 'G3'),
  ('MEN_MOTORBIKE_BOOTS', 'G3'),
  ('MEN_ROLLER_SKATES_BLADES', 'G3'),
  ('SPORT_SHOES_RUNNING_MEN', 'G3'),
  ('MEN_SKI_BOOTS', 'G3'),
  ('MEN_SNOWBOARD_BOOTS', 'G3'),
  ('MEN_SWIMMING_WATER_SHOES', 'G3'),
  ('MEN_TENNIS_SHOES', 'G3'),
  ('MEN_SNEAKERS', 'G3'),
  ('MEN_ACC_BAG_BACKPACKS', 'G1'),
  ('MEN_BRIEFCASES', 'G1'),
  ('MEN_ACC_BUMBAGS', 'G1'),
  ('MEN_GYM_BAGS', 'G1'),
  ('MEN_HOLDALLS', 'G1'),
  ('MEN_LUGGAGE', 'G1'),
  ('MEN_ACC_SATCHELS', 'G1'),
  ('MEN_ACC_BAG_SHOULDER_BAGS', 'G1'),
  ('WALLETS', 'G1'),
  ('MEN_WASH_BAGS', 'G1'),
  ('MEN_BANDANAS_HEADSCARVES', 'G1'),
  ('MEN_ACC_BELTS', 'G1'),
  ('MEN_BRACES', 'G1'),
  ('MEN_ACC_GLOVES', 'G1'),
  ('MEN_HANDKERCHIEFS', 'G1'),
  ('MEN_BALACLAVAS', 'G1'),
  ('MEN_BEANIES', 'G1'),
  ('MEN_ACC_HAT_CAPS', 'G1'),
  ('MEN_ACC_HAT_HATS', 'G1'),
  ('MEN_POCKET_SQUARES', 'G1'),
  ('SCARVES_SHAWLS', 'G1'),
  ('MEN_ACC_SUNGLASSES', 'G1'),
  ('MEN_TIES_BOWTIES', 'G1'),
  ('MEN_ACC_WATCHES', 'G1'),
  ('MEN_ACC_OTHER', 'G1'),
  ('FULL_ROMPERS_GIRLS_NEW', 'G2'),
  ('GIRLS_COMBI_PILOTES_NEW', 'G2'),
  ('KID_SLEEPSACK', 'G2'),
  ('GIRLS_BODIES_NEW', 'G2'),
  ('ROMPERS_GIRLS_NEW', 'G2'),
  ('SETS_GIRLS_NEW', 'G2'),
  ('GIRLS_BABIES_OTHERS', 'G2'),
  ('BABY_GIRLS_SHOES_NEW', 'G3'),
  ('BOOTS_GIRLS_NEW', 'G3'),
  ('FLAT_GIRLS_NEW', 'G3'),
  ('GIRLS_FLIP_FLOPS_SANDALS_SLIDES', 'G3'),
  ('SHOES_OCC_GIRLS_NEW', 'G3'),
  ('GIRLS_HEELS', 'G3'),
  ('SLIPPERS_GIRLS_NEW', 'G3'),
  ('GIRLS_SPORT_SHOES', 'G3'),
  ('SNEAKERS_GIRLS_NEW', 'G3'),
  ('COATS_GIRLS_NEW', 'G2'),
  ('OUT_VESTS_GIRLS_NEW', 'G2'),
  ('JACKETS_GIRLS_NEW', 'G2'),
  ('GIRLS_RAIN_GEAR', 'G2'),
  ('GIRLS_SNOW_GEAR', 'G2'),
  ('SWEATERS_GIRLS_NEW', 'G2'),
  ('VNECK_SWEATERS_GIRLS_NEW', 'G2'),
  ('TURLENECK_GRILS_NEW', 'G2'),
  ('ZIPP_SWEATERS_GIRLS_NEW', 'G2'),
  ('BOLEROS_GIRLS_NEW', 'G2'),
  ('HOODIES_GIRLS_NEW', 'G2'),
  ('VESTS_GIRLS_NEW', 'G2'),
  ('OTHER_SWEATERS_GIRLS', 'G2'),
  ('TOPS_GIRLS_NEW', 'G2'),
  ('POLOSHIRTS_GIRLS_NEW', 'G2'),
  ('SHIRTS_GIRLS_NEW', 'G2'),
  ('SHORTSLEEVE_SHIRTS_GIRLS_NEW', 'G2'),
  ('LOGSLEEVE_SHIRTS_GIRLS_NEW', 'G2'),
  ('SLEEVELESS_SHIRTS_GIRLS_NEW', 'G2'),
  ('TUNICS_GIRLS_NEW', 'G2'),
  ('OTHER_TOPS_GIRLS', 'G2'),
  ('SHORTDRESSES_GIRLS_NEW', 'G2'),
  ('LONGDRESSES_GIRLS_NEW', 'G2'),
  ('GIRLS_SKIRTS', 'G2'),
  ('JEANS_GIRLS_NEW', 'G2'),
  ('SKINNYPANTS_GIRLS_NEW', 'G2'),
  ('BELLBOTTOMPANTS_GIRLS_NEW', 'G2'),
  ('LEGGINGS_GIRLS_NEW', 'G2'),
  ('JOGGINGS_GIRLS_NEW', 'G2'),
  ('OVERALLS_ROMPERS_GIRLS_NEW', 'G2'),
  ('GIRLS_SHORTS', 'G2'),
  ('HAREM_GIRLS_NEW', 'G2'),
  ('OTHER_PANTS_GIRLS', 'G2'),
  ('HATS_GIRLS_NEW', 'G2'),
  ('SWIMSUITS_GIRLS_NEW', 'G2'),
  ('BIKINIS_GIRLS_NEW', 'G2'),
  ('BATHROBES_GIRLS_NEW', 'G2'),
  ('SOCKS_GIRLS_NEW', 'G3'),
  ('TIGHTS_GIRLS_NEW', 'G3'),
  ('PANTIES_GIRLS_NEW', 'G2'),
  ('ONEPIECE_PAJAMAS_GIRLS', 'G2'),
  ('TWOPIECE_PAJAMAS_GIRLS_NEW', 'G2'),
  ('NIGHTGOWNS_GIRLS_NEW', 'G2'),
  ('GIRLS_SPORTS', 'G2'),
  ('CLOTHING_PACKAGES_NEW', 'G2'),
  ('COSTUMES_GIRLS_NEW', 'G2'),
  ('THEMED_COSTUMES_NEW', 'G2'),
  ('GIRLS_OTHER', 'G2'),
  ('FULL_ROMPERS_BOYS_NEW', 'G2'),
  ('BOYS_COMBI_PILOTES_NEW', 'G2'),
  ('KID_SLEEPSACK_BOYS_NEW', 'G2'),
  ('BOYS_BODIES_NEW', 'G2'),
  ('ROMPERS_BOYS_NEW', 'G2'),
  ('BOYS_SETS_NEW', 'G2'),
  ('OTHER_BABY_BOYS', 'G2'),
  ('BOY_BABYSHOES_NEW', 'G3'),
  ('BOYS_BOAT_LOAFERS_MOCCASINS', 'G3'),
  ('BOOTS_BOYS_NEW', 'G3'),
  ('BOYS_ESPADRILLES', 'G3'),
  ('BOYS_FLIP_FLOPS_SANDALS_SLIDES', 'G3'),
  ('SHOES_OCC_BOYS_NEW', 'G3'),
  ('SLIPPERS_BOYS_NEW', 'G3'),
  ('BOYS_SPORT_SHOES', 'G3'),
  ('SNEAKERS_BOYS_NEW', 'G3'),
  ('BOYS_COATS_NEW', 'G2'),
  ('BOYS_OUTVESTS_NEW', 'G2'),
  ('BOYS_JACKETS_NEW', 'G2'),
  ('BOYS_RAIN_GEAR', 'G2'),
  ('BOYS_SNOW_GEAR', 'G2'),
  ('SWEATERS_BOYS_NEW', 'G2'),
  ('VNECK_SWEATERS_BOYS_NEW', 'G2'),
  ('TURLENECK_BOYS_NEW', 'G2'),
  ('ZIPP_SWEATERS_BOYS_NEW', 'G2'),
  ('HOODIES_BOYS_NEW', 'G2'),
  ('VESTS_BOYS_NEW', 'G2'),
  ('OTHER_SWEATERS_BOYS', 'G2'),
  ('TSHIRTS_BOYS_NEW', 'G2'),
  ('POLOSHIRTS_BOYS_NEW', 'G2'),
  ('SHIRTS_BOYS_NEW', 'G2'),
  ('SHORTSLEEVE_SHIRTS_BOYS_NEW', 'G2'),
  ('LONGSLEEVE_BOYS_NEW', 'G2'),
  ('SLEEVELESS_SHIRTS_BOYS_NEW', 'G2'),
  ('OTHER_TOPS_BOYS', 'G2'),
  ('JEANS_BOYS_NEW', 'G2'),
  ('SKINNYPANTS_BOYS_NEW', 'G2'),
  ('BELLBOTTOMPANTS_BOYS_NEW', 'G2'),
  ('BOYS_LEGGINGS_NEW', 'G2'),
  ('BOYS_JOGGINGS_NEW', 'G2'),
  ('OVERALLS_ROMPERS_BOYS_NEW', 'G2'),
  ('BOYS_SHORTS', 'G2'),
  ('BOYS_PANTS_HAREM', 'G2'),
  ('BOYS_OTH_PANTS', 'G2'),
  ('CAPS_BOYS_NEW', 'G2'),
  ('BATHSHORTS_BOYS_NEW', 'G2'),
  ('BATHROBES_BOYS_NEW', 'G2'),
  ('SOCKS_BOYS_NEW', 'G3'),
  ('TIGHTS_BOYS_NEW', 'G3'),
  ('PANTIES_BOYS_NEW', 'G2'),
  ('OTHER_UNDER_BOYS', 'G2'),
  ('ONEPIECE_PAJAMAS_BOYS', 'G2'),
  ('TWOPIECE_PAJAMAS_BOYS', 'G2'),
  ('BOYS_SPORTS', 'G2'),
  ('BOYS_PACKAGES', 'G2'),
  ('TWINS_BOYS_NEW', 'G2'),
  ('OCC_BOYS_NEW', 'G2'),
  ('BOYS_THEMED_COSTUMES', 'G2'),
  ('BOYS_OTHER', 'G2'),
  ('BABY_BATH_ACC', 'G2'),
  ('SPORT_HORSE_GLOVES', 'G1'),
  ('SPORT_WATER_WETSUITS', 'G1'),
  ('SPORT_WATER_PFD', 'G1'),
  ('SPORT_MARTIAL_GLOVES', 'G1'),
  ('SPORT_GOLF_GLOVES', 'G1')
)
insert into public.platform_category_aspects
  (platform, category_key, field_key, field_label, required, input_type, allowed_values, source)
select 'opla', f.category_key, 'size', 'Taille', true, 'select', g.allowed_values, 'manual'
  from feuilles f join grilles g on g.nom = f.nom
on conflict (platform, category_key, field_key) do update
  set allowed_values = excluded.allowed_values,
      field_label    = excluded.field_label,
      input_type     = excluded.input_type,
      required       = excluded.required,
      source         = excluded.source,
      last_seen_at   = now();

commit;
