-- ══════════════════════════════════════════════════════════════════════════════
-- CAPTURE DE LA PROD (audit dépôt ↔ prod du 26/09/2026)
-- Migration 20260919132225 « rapatriement_socle_tables » : APPLIQUÉE en prod, mais aucun fichier
-- ne la portait dans le dépôt. Ce fichier reprend MOT POUR MOT les instructions
-- enregistrées dans supabase_migrations.schema_migrations.statements — il ne
-- change rien en prod (même version déjà inscrite dans l'historique distant).
-- ⛔ Ne pas réappliquer à la main.
-- ══════════════════════════════════════════════════════════════════════════════
CREATE TABLE IF NOT EXISTS public.ventes (
  id                 bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at         timestamptz NOT NULL DEFAULT now(),
  titre              text,
  prix_achat         numeric,
  prix_vente         numeric,
  benefice           numeric,
  date               date,
  user_id            uuid,
  marque             text,
  type               text,
  description        text,
  emplacement        text,
  plateforme         text,
  quantite           integer,
  inventaire_id      bigint,
  statut             text,
  selling_fees       numeric,
  plateforme_code    text,
  plateforme_origine text,
  vendu_le           timestamptz,
  commande_ref       text,
  source             text,
  releve_le          timestamptz,
  devise             text,
  frais_plateforme   numeric
);

ALTER TABLE public.ventes ENABLE ROW LEVEL SECURITY;

GRANT SELECT, INSERT, UPDATE, DELETE ON public.ventes TO anon;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.ventes TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES, TRIGGER, TRUNCATE
  ON public.ventes TO service_role;

create table if not exists public.job_relaunch_log (
  id         bigserial primary key,
  job_id     uuid        not null references public.cross_post_jobs(id) on delete cascade,
  user_id    uuid        not null,
  statut     text        not null check (statut in ('sent','skipped_extension_active')),
  cas        smallint,
  created_at timestamptz not null default now(),
  unique (job_id, statut)
);

create index if not exists job_relaunch_log_user_idx
  on public.job_relaunch_log (user_id, created_at desc);

grant select, insert, update, delete on public.job_relaunch_log to authenticated;
grant usage, select on sequence public.job_relaunch_log_id_seq to authenticated;

alter table public.job_relaunch_log enable row level security;

drop policy if exists job_relaunch_log_self on public.job_relaunch_log;
create policy job_relaunch_log_self on public.job_relaunch_log
  for select to authenticated using (auth.uid() = user_id);

CREATE TABLE IF NOT EXISTS public.lbc_grilles_relevees (
  id            bigserial PRIMARY KEY,
  user_id       uuid        REFERENCES auth.users(id) ON DELETE CASCADE,
  job_id        uuid,
  category_key  text,
  field_key     text,
  champ         text,
  valeur_demandee text,
  options       jsonb NOT NULL,
  n_options     integer,
  contexte      jsonb,
  handler_build text,
  releve_at     timestamptz NOT NULL DEFAULT now()
);

COMMENT ON TABLE public.lbc_grilles_relevees IS
  'Append-only. Chaque menu Leboncoin ouvert pendant un dépôt : la grille complète + le contexte des autres critères. Sert à identifier le discriminant entre grilles d''une même catégorie (4 grilles sous Mode > Vêtements au 10/09).';

CREATE INDEX IF NOT EXISTS lbc_grilles_relevees_cat_field_idx
  ON public.lbc_grilles_relevees (category_key, field_key, releve_at DESC);

GRANT SELECT, INSERT, UPDATE, DELETE ON public.lbc_grilles_relevees TO authenticated;
GRANT USAGE, SELECT ON SEQUENCE public.lbc_grilles_relevees_id_seq TO authenticated;

ALTER TABLE public.lbc_grilles_relevees ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS lbc_grilles_relevees_insert_self ON public.lbc_grilles_relevees;
CREATE POLICY lbc_grilles_relevees_insert_self ON public.lbc_grilles_relevees
  FOR INSERT TO authenticated WITH CHECK (user_id = auth.uid());

DROP POLICY IF EXISTS lbc_grilles_relevees_select_self ON public.lbc_grilles_relevees;
CREATE POLICY lbc_grilles_relevees_select_self ON public.lbc_grilles_relevees
  FOR SELECT TO authenticated USING (user_id = auth.uid());
